### ISSUE TITLE
[RF] Problems with binning in `createHistogram`

### ISSUE THREAD

**Issue by cburgard** [root-project/root#10401]
- [ ] Checked for duplicates

### Describe the bug

Under some circumstances, `createHistogram` creates histograms with a binning that does not reflect the "correct" binning of the observable.
In general, it should be true that especially for workspaces generated with HistFactory, the histograms created with `createHistogram` from the various category Pdfs and datasets should have the same binning as the input histograms given to HistFactory.
However, that is not always the case.
I haven't figured out yet what the exact conditions are under which this fails and cannot at the moment provide a reproducer, but I'd like to suggest adding a few unit tests that create a workspace with HistFactory with different binnings, and then use `createHistogram` to create histograms from the input.
The resulting histograms should always match the input in content (save for negative or 0 bin contents) and bin count and boundaries.

I will follow up with a reproducer if I manage to create one.

### Additional context
Possibly related: https://github.com/root-project/root/pull/1916

**Comment by cburgard** [comment]
In the latest case I encountered, the isuse was present for a dataset (not a Pdf). 
The combined dataset was split into its components using the `split` method. Then, `createHistogram` was called (this signature: https://root.cern.ch/doc/master/classRooDataSet.html#aa716cef587238f4cdd82b6a00329dbb4) on each of the component datasets. For one of the channels, the binning of the dataset was incorrect.
The behavior could be fixed by supplying the optional arguments with the bin counts taken from the observables (`RooRealVar::getBins()`). It was only tested for 1D. This workaround works for histograms remapped to the range 0-1, but not for other histograms with different ranges. The reasons for this are unclear at the moment. 
It's also unclear why this problem occurs for some regions, but not for others.

**Comment by guitargeek** [comment]
Hi @cburgard, the answer to the riddle is in the documentation of `RooAbsData::createHistogram`:
https://root.cern.ch/doc/master/classRooAbsData.html#ae85313ede76138ccb4ffc2e6be58d827

> The range of each observable that is histogrammed is always automatically calculated from the distribution in the dataset.

That's why you get a completely different binning. However, I don't think this is the good behavior, and the default should be to take the binning from the RooFit variable, just like the other overload of `RooAbsData::createHistogram` does:
https://root.cern.ch/doc/master/classRooAbsData.html#aa716cef587238f4cdd82b6a00329dbb4
That one is more common, so I think it's behavior should also be mimicked in the overload that you are using. I have opened a PR to make that behavior consistent:

https://github.com/root-project/root/pull/10405

Does that fix your issue?

**Comment by guitargeek** [comment]
Please use the overload of `RooAbsData::createHistogram` with the RooFit command arguments, which doesn't showcase this confusing behavior. To avoid confusion in the future, the overload that you used with the int parameters is deprecated now, which should solve the issue. Let me know if that's fine for you!
