### ISSUE TITLE
[RF] `RooDataSet.from_numpy` clips the values instead of skipping events

### ISSUE THREAD

**Issue by nikoladze** [root-project/root#10447]
- [X] Checked for duplicates

### Describe the bug
When i create a `RooDataSet` from a numpy array using `RooDataSet.from_numpy` the values are "clipped" to the range of the `RooRealVar` (setting values outside the bounds to the values at the boundary)

probably caused by this code:
https://github.com/root-project/root/blob/e4e8e62c2a04bd5c167b69118bf1afba7b35081b/bindings/pyroot/pythonizations/python/ROOT/_pythonization/_roofit/_roodataset.py#L101-L102

### Expected behavior
I think it should instead skip events outside of the range. When i import a TTree instead events will be skipped.

### To Reproduce
```python
import ROOT
import numpy as np
x = ROOT.RooRealVar("x", "", 2, 5)
rds = ROOT.RooDataSet.from_numpy({"x": np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])}, [x])
list(rds.store().realStoreList().data().data())
```
gives me
```
[2.0, 2.0, 3.0, 4.0, 5.0, 5.0, 5.0, 5.0, 5.0]
```
Compared to the TTree version:
```python
ROOT.RDF.MakeNumpyDataFrame({"x": np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])}).Snapshot("tree", "npdf.root")
f = ROOT.TFile.Open("npdf.root")
tree = f.Get("tree")
rds = ROOT.RooDataSet("", "", [x], ROOT.RooFit.Import(tree))
list(rds.store().realStoreList().data().data())
```
gives me
```
[2.0, 3.0, 4.0, 5.0]
```

### Setup
```
ROOT Version: 6.26/00
Built for linuxx8664gcc on Mar 03 2022, 06:51:13
From tags/v6-26-00@v6-26-00
```
installed on archlinux with pacman

### Additional context
Thanks a lot for creating these pythonizations! I think this is really nice, making pyROOT interoperable with the rest of the python ecosystem!

**Comment by guitargeek** [comment]
Hi, thanks for pointing out that this clipping is inconsistent with the TTree version!

I designed the numpy version to be consistent with filling a RooDataSet one-by-one with `RooDataSet::add()`, in which case the value is clipped.

That's a general problem in RooFit, many ways to do the same thing and they behave inconsistently.

However, I think both clipping and skipping can be very dangerous. I'm about to change the behavior to simply erroring out when the values are not in the range, with the possibility to manually change that behavior to skipping or clipping if desired. Like that, there are no bad surprises. Any thoughts on that?

This issue is related to https://github.com/root-project/root/issues/6937. Probably I will address them together in one PR.

**Comment by nikoladze** [comment]
> However, I think both clipping and skipping can be very dangerous. I'm about to change the behavior to simply erroring out when the values are not in the range, with the possibility to manually change that behavior to skipping or clipping if desired. Like that, there are no bad surprises. Any thoughts on that?

That sounds very reasonable. I would have intuitively assumed that the values are skipped, but if the clipping behavior also exists in the interface others might have assume that. Then it's probably best to force the users to decide.

**Comment by guitargeek** [comment]
Just as a note for myself when I fix this: a related problem that can be fixed in the same PR is that the DataSet construction is overly verbose when the TTree contains a category index value that is not covered by the `RooCategory` definition:
https://root.cern/doc/master/rf401__importttreethx_8C.html
