### ISSUE TITLE
AdditionalData is not exported to XML

### ISSUE THREAD

**Issue by jndrf** [root-project/root#10538]
- [x] Checked for duplicates

### Describe the bug

I tried to create "additional" datasets for one RooFit sample. They do not show up in the XML file (and it seems also not in the root file of the model). When discussing this with @cburgard , we found that the `fAdditionalData` member of `Channel` [is supposed to hold additional datasets to be added to the XML](https://github.com/root-project/root/blob/c8d49336b666355553879aea9448f7e9588ecb5e/roofit/histfactory/inc/RooStats/HistFactory/Channel.h#L96), but [is never used in `Channel::XML](https://github.com/root-project/root/blob/c8d49336b666355553879aea9448f7e9588ecb5e/roofit/histfactory/src/Channel.cxx#L105).

### Expected behavior

The additional datasets also get exported to XML/rootfile/etc.
### To Reproduce

Add an additional data sample to a workspace, save it.

I have modified one of the python examples so that it should reproduce this issue.
It was first discovered in our analysis framework.
[histfactoryxmlexport.py.txt](https://github.com/root-project/root/files/8641363/histfactoryxmlexport.py.txt)

### Setup

Both with ROOT 6.20/06 from `AnalysisBase,21.2.204` and ROOT 6.24/06 from [LCG_101_ATLAS_20](https://lcginfo.cern.ch/release/101_ATLAS_20/)

**Comment by guitargeek** [comment]
Hi! I have opened a PR to implement the additional dataset feature correctly.

For my curiosity, what is the usecase of defining additional datasets?

**Comment by cburgard** [comment]
The use case in question is like this:
For reasons of cross-validation, it has become a customary technique within ATLAS (and probably other collaborations as well) to construct a "Hybrid Dataset", that is equal to the real data in the control regions, but only contains asimov data in the signal region ("partically unblinded"). If you want to have both the Hybrid Dataset and the Dataset in the same workspace to reduce the bookkeeping and turnaround time of the unblinding procedure (first only look at hybrid data, and if the fit to hybrid data looks okay, also look at real data), the most convenient way to do this would be to include it from the get-go using this feature, rather than having to somehow construct or import it down the line when the workspace already exists, or to maintain two completely different workspaces that have the same model and only different datasets.

**Comment by jndrf** [comment]
Hi @guitargeek, I want to fit to data in the control regions, but, since the analysis is blinded, fit only to Asimov data in the signal region. This "additional data" mechanism seems to allow exactly that.

**Comment by guitargeek** [comment]
Hi, thanks for the explanation! Okay that's a very valid usecase. After all, the workspace already contains `obsData` and `asimovData`, so it's natural to also add the hybrid dataset.
