### ISSUE TITLE
[PyROOT] Functions with `const char*` arguments can't accept `ROOT.nullptr`

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#10954]
### Describe the bug

It is not possible to pass `ROOT.nullptr` to a function that takes a `const char*`.

### Expected behavior

A `ROOT.nullptr` should by accepted by cppyy overloads when a `const char*` is expected.

In RooFit, it happens often that the user is expected to pass `nullptr`, for example in [RooAbsArg::setStringAttribute()](https://root.cern.ch/doc/master/classRooAbsArg.html#a3792b218558aba2552f432fbd4d91c9c), where passing a `nullptr` removes an attribute with a given name. So it would be great if PyROOT supports that!

### To Reproduce

```Python
import ROOT

ROOT.gInterpreter.Declare("""
void foo(char*) {}
void bar(const char*) {}
""")

ROOT.foo(ROOT.nullptr) # works!
ROOT.bar(ROOT.nullptr) # doesn't work
```

### Setup

ROOT `master` on Arch Linux.

**Comment by etejedor** [comment]
This is actually a convention that is followed for `const char*` in cppyy and was already there in old PyROOT: it converts from Python strings (or from ctypes c_char_p). This can be seen [here](https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx#L1089). `char*` tries string first but has a [fallback case] for char buffers (https://github.com/root-project/root/blob/master/bindings/pyroot/cppyy/CPyCppyy/src/Converters.cxx#L1346), which explains why it accepts nullptr.

In the kind of API that you describe, wouldn't it be better to have a method to remove a key with a given name, instead of using the setter with a null pointer?
