### ISSUE TITLE
[DF] Some special characters in Filter titles break `SaveGraph`

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#11173]
Reproducer:

```cpp
#include <ROOT/RDataFrame.hxx>
#include <ROOT/RDFHelpers.hxx>
#include <cstdlib>

int main()
{
   auto df = ROOT::RDataFrame(10).Filter("rdfentry_ > 0", "Title with special chars: !@#$%^&*()-=_+{}[]<>?/");
   ROOT::RDF::SaveGraph(df, "out.dot");
   std::system("dot -Tpng out.dot > out.png");
}
```

yields:

```
Error: not well-formed (invalid token) in line 1
... <HTML>Title with special chars: !@#$%^&*()-=_+{}[] ...
in label of node 1
```

`out.dot` has the following contents:

```dot
digraph {
	1 [label=<Title with special chars: !@#$%^&*()-=_+{}[]<>?/>, style="filled", fillcolor="#0f9d58", shape="hexagon"];
	0 [label=<Empty source<BR/>Entries: 10>, style="filled", fillcolor="#f4b400", shape="ellipse"];
	0 -> 1;
}
```

and changing it to the following seems to fix the problem (enclosing `label` value between quotes rather than between `<>`, substituting `<BR/>` with `\n`:

```dot
digraph {
	1 [label="Title with special chars: !@#$%^&*()-=_+{}[]<>?/", style="filled", fillcolor="#0f9d58", shape="hexagon"];
	0 [label="Empty source\nEntries: 10", style="filled", fillcolor="#f4b400", shape="ellipse"];
	0 -> 1;
}
```

@ikabadzhov I am not sure whether we need to use HTML rather than plain strings for something else than line breaks. If not, then the two simple substitutions above might be a viable fix.

**Comment by ikabadzhov** [comment]
Okay. I used htmls in every possible SaveGraph "bubble type" (e.g. datasource/define/filter/actions for consistency).

The actual reason to move to html is that in the action node, I want to use a smaller font to say that the action has run, e.g.:
```
<BR/><FONT POINT-SIZE=\"10.0\">Already Run</FONT>
```

There are 2 possible solutions:


1. Move all "bubble types" to plain text -- `Already Run` would appear slightly larger:
![out](https://user-images.githubusercontent.com/46775299/185161238-f0dd3d47-9bc3-49ee-90c6-766b860d2a90.png)

2. Keep only the actions as an html:
![out2](https://user-images.githubusercontent.com/46775299/185161401-c014eb40-5423-4907-b3c0-4934e21f27c0.png)

I am currently migrating to solution 1, as I think it is more consistent and still it is clear that the action has run (it is also in different color because it is run).

**Comment by eguiraud** [comment]
2. sounds good since action names can also be user-defined sometimes.
