### ISSUE TITLE
Interpreter warns when calling [[nodiscard]] functions

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#11562]
Similar to https://github.com/root-project/root/issues/8622, but in the interpreter:
```
root [0] std::vector<int> v;
root [1] v.size()
ROOT_prompt_1:1:1: warning: ignoring return value of function declared with 'nodiscard' attribute [-Wunused-result]
v.size()
^~~~~~
(unsigned long) 0
```
(with libstdc++12)

This currently makes `roottest-cling-stl-default-VectorSort` fail with GCC 12.

**Comment by jalopezg-r00t** [comment]
Thanks for the report, @hahnjo!

IIRC, this one was not trivial to fix, as in principle, we only want to ignore `diag::warn_unused_result` if _(i)_ value capture is enabled, and _(ii)_ only for the last parsed statement.
However, as the diagnostic is emitted during parsing (see `SemaStmt.cpp`), I think the only way of conditionally emitting this diagnostics -given the two conditions above-, would be to buffer all the diagnostics and then filter this one based on the `cling::CompilationOptions` and the source location.

Otherwise, we can always fallback to the naive fix of just disable/filter this diagnostic in every case.

**Comment by hahnjo** [comment]
Yes, I agree this is non-trivial to fix after reading through https://github.com/root-project/root/issues/8622. But I decided to open an issue just to keep track of the problem because it affects a test with GCC 12; not sure if we can do anything for that one in particular in the test code...
