### ISSUE TITLE
Permission denied !!

### ISSUE THREAD

**Issue by Anas-Alaali** [root-project/root#11636]
When I was trying to enable pythia for STARlight simulation
 
![Screenshot 2022-10-26 011826](https://user-images.githubusercontent.com/116489914/197894582-ab551b9e-426a-4677-aac2-505acfba56a2.png)

I got this 

![Screenshot 2022-10-26 012032](https://user-images.githubusercontent.com/116489914/197894542-a760c5da-1d28-43a0-9de4-cbf41e236ba5.png)

How can I fix that? 
Note: this is ubuntu WSL

**Comment by pamputt** [comment]
I think it is better for you to ask help on the ROOT forum instead of on the issues section on Github. Actually, you have already posted a message on the forum [here](https://root-forum.cern.ch/t/permission-denied/52089/2).
So I think, this issue and [this one](https://github.com/root-project/root/issues/11626) should be closed.

**Comment by guitargeek** [comment]
Right, and the problem also doesn't appear to be related to ROOT.

In any case, if it turns out that the question is related to ROOT, let us continue discussing on the forum :+1:
