### ISSUE TITLE
[RF] ROOT v6.26/08 plots wrong pull distribution with RooPlot::pullHist

### ISSUE THREAD

**Issue by ciccinocino** [root-project/root#11738]
- [x] Checked for duplicates

### Describe the bug
With the recent version of ROOT (v6.26/08), I found out that when plotting the pull distribution after a fit with pullHist, the wrong distribution is shown with respect to the one produced with ROOT v6.26/06, for example

### Expected behavior
When the fit converges, a gaussian-like pull distribution is expected, while with ROOT v6.26/08 the histogram bars are unreasonably high

### To Reproduce
You can find the needed code and data to reproduce the bug at the following link:
https://cernbox.cern.ch/s/hnMmXVjUtbwlZJN
Simply run `bug_reproducer.py` with ROOT v6.26/06 and v6.26/08 and see the difference in the plot produced

### Setup
Tested with ROOT setup from `lb-conda`

**Comment by guitargeek** [comment]
See also the original forum post:
https://root-forum.cern.ch/t/root-v6-26-08-pullhist-shows-wrong-distribution/52417/4

**Comment by guitargeek** [comment]
Hi @ciccinocino, thanks for opening this issue! I realize know that this is a solved issue where the fix is already in `master`:
https://github.com/root-project/root/pull/11566

However, there is no backport to the 6.28 branch yet, but I created it now:
https://github.com/root-project/root/pull/11748

Sorry for the delay in this! Once a new 6.28 patch release is out, i.e. 6.26.12, this will be fixed again!
