### ISSUE TITLE
Make ROOT terminology and workings easier to decypher

### ISSUE THREAD

**Issue by bobOnGitHub** [root-project/root#11967]
### Explain what you would like to see improved

Documentation. 

I am having to spend way too much time trying to figure out what basic stuff is.

Eg. a TTree is apparently a list of "independent columns" but so far looks to me very much like it is the equivalent of a table used to back a higher level representation of table in which case the columns are not independent - they would be related (unless "independent columns" is being used to mean statistically independent variables).

And I came across "event" in code comments which sounds very like "event" is a "row" of data which'd make sense from a Cern perspective but is ambiguous/meaningless/confusing to a newbie.

### share how it could be improved

A Glossary with ROOT term equivalents in other frames of reference

Eg.

Event ~ row ~ tuple ~ observation (assuming I guessed correctly)

TTRee ~ RDataFrame/TDataFrame ~ dataset ~ Table ~ 1 or 2 dimensional Array or Tensor ~  a grid of data with one row per event/observation/record.
TBranch ~ column of data in a grid or table of data
TLeaf  ~ element ~ cell - a single observation of single variable

And where these are not correct list the differences between them to clarify what they actually are.

Without a clear and precise understanding of what the terms mean you are never sure about what you are doing.

----------------------------------------------------------
Some (more) high level notes on how the framework works would be very useful at the start of the primer or comments in the code to explain "magic" when it happens - I was scratching my head as to how one particular object knew to use another when no relationship appeared in the code anywhere;
```

   // The canvas on which we'll draw the graph
    auto  mycanvas = new TCanvas();

 // lots of code like...

    // Draw the graph !
    graph.DrawClone("APE");

// but no mention of mycanvas again until...    

    mycanvas->Print("graph_with_law.pdf");
```

which raises all sorts of questions ( as it is not obvious what is going on ).
 
------------------------------------------------------------

Basic stuff first: 

Most people will want to read in a multi column file and get stats/analysis on those columns - fromCSV is buried pretty deep considering - why why why am I reading about "TTree"s when I can get going without it ?

**Comment by HenryDayHall** [comment]
(I'm not part of the root team, just someone who uses this a lot)

There are a few things you may already be aware of, but if not might be helpful;

1. The [uproot](https://github.com/scikit-hep/uproot5) library; if all you are doing is reading from root format files and then processing with other libraries, then uproot is a much lighter weight, more modern feeling, way to read data. You don't need root installed at all to use it. Afaik, it's only got  a python api, so you would still need root for c++ stuff.

2. The reason for all the TThis and TThat is the [Taligent](https://root.cern/TaligentDocs/TaligentOnline/DocumentRoot/1.0/Docs/books/WM/WM_63.html#HEADING77) naming standard. That made a lot more sense of things for me.

3. The official root docs are fairly nicely presented. E.g https://root.cern.ch/doc/master/classTTree.html which does start by doing it's best to describe what the heck a TTree is.

Perhaps in a sense the official docs are a glossary, just not a very complete one yet? TTree and TLeaf are both well documented, TBranch is a bit sketcher. Possibly because we aren't meant to handle them directly too often.

Most of your suggested translations are a reasonable description of the basic function of those classes, but sometimes it gets more complicated. For example, a TTree can be a rectangular array, but it's more often a ragged array. Also a TBranch may in fact hold compiled objects, or even just a part of a compiled object.

**Comment by couet** [comment]
https://root.cern/manual/
https://root.cern/primer/

**Comment by bobOnGitHub** [comment]
@HenryDayHall, @couet 

I _was_ working through the online materials when I became frustrated and posted the issue. Eg. the "magic" code issue relates to content in the primer.

Not sure if/when I'll get a chance/excuse to look at ROOT again. Nice ideas though - particularly Cling and the interactive ui functionality.  

On the other hand a quick search on how to do bubble charts in ROOT led to some depressing results.

**Comment by couet** [comment]
@bobOnGitHub Ok can we close this issue thought? if not can you tell us what should be improved?
