### ISSUE TITLE
error on ROOT VM download

### ISSUE THREAD

**Issue by Fesfandi** [root-project/root#12158]
Hi,
I am trying to download the ROOT VM from the https://cernbox.cern.ch/index.php/s/ZF5pffhZuZjwgAI, but there is an UNKNOWN ERROR while entering this link. would you please help me on this error?

**Comment by vepadulano** [comment]
Hi @Fesfandi ,

I am not completely sure what you mean by "ROOT VM" and I don't think there is any release package shipped via cernbox. To install ROOT, please follow the installation instructions at https://root.cern/install

**Comment by Fesfandi** [comment]
Hi Vincenzo,

I mean the ROOT virtual machine which can be mounted on a virtual box. It
is suggested in
https://github.com/root-project/training/tree/master/BasicCourse.

Best,
Fatemeh

**Comment by vepadulano** [comment]
This is just my guess, but by reading the README at the link you mention it looks like that VM was made for the purpose of that particular training (5 years ago) and not with a wider scope in mind. You can surely create your own VM with the Linux flavor of your choice (probably a Fedora image would be easier to use), then install ROOT normally when you launch that VM. Otherwise, you can take a look at ROOT Docker containers for a possibly even easier experience at https://hub.docker.com/r/rootproject/root

**Comment by vepadulano** [comment]
Hi @Fesfandi ,

Do you have any updates on this? If not, I will close the issue in a couple of days. If you find different errors when installing ROOT through one of the official ways, please open another issue or ask about it on the [forum](root-forum.cern.ch)

**Comment by dpiparo** [comment]
Closing the issue given the explanation given by @vepadulano . Feel free to look for help on the forum in case issues are encountered with ROOT installations!
