### ISSUE TITLE
CI: roottest CI

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#12271]
We need to build ROOT and run roottest as part of roottest's CI (i.e. for the roottest repo)

**Comment by dpiparo** [comment]
In case a developer has 2 PRs that belong together logically, one for root and one for roottest, no change is needed, because as long as the branches have the same name, the CI matches the two for the root build+tests. This is the most common case, by far.

Changes can be proposed to roottest only via a PR, and in order to test them, currently, one needs a "placeholder PR", created starting from a branch with the same name of the one used for the roottest PR. 

However, the latter case is far rarer than the former one. The work at the level of runners and workflows would be rather complex to achieve the aforementioned goal, when we have a solution, that has to be applied rarely. I am closing this item as "Won't fix" (not needed would fit better)
