### ISSUE TITLE
[ci] Make it possible to force a CI build from scratch

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#12302]
For some types of changes incremental builds are expected to fail (e.g. if source files are moved or removed).

For those cases we probably need a way to ask the CI to rebuild from scratch rather than perform an incremental build.

**Comment by olemorud** [comment]
@eguiraud I've briefly experimented with using keywords in the PR body/title. The problem is that you have to close and re-open the issue to trigger a new build. Clicking 're-run jobs' unintuitively starts a job using the old PR title/body.

Would using comments to start a new build from scratch be a better interface? (Something like commenting `/build`)

**Comment by Axel-Naumann** [comment]
PR builds are incremental, and if the build fails *due to the changes introduced by the PR* then indeed we need some way to signal that we need a full build. Maybe a label?

> due to the changes introduced by the PR

If it's due to some other change in main, introduced between the last artifact and master, unrelated to the PR, then just waiting for the new artifacts to be generated should be fine?

**Comment by eguiraud** [comment]
> Maybe a label?

99% of the times PR submitters will not realize that they needed a full build rather than an incremental before it's too late.
As long as the label changes the CI's behavior even if it's added after the fact (after the first build), it sounds like a good solution because it stays there permanently.

> Would using comments to start a new build from scratch be a better interface? (Something like commenting /build)

A command like `/build` (currently we have `@phsft-bot build [...options...]`) would be slightly worse than a label because on any new push to the PR you would still get an incremental build, and you would have to give the special `/build` command every time, I guess.

**Comment by olemorud** [comment]
> Maybe a label?

The 're-run jobs' button uses the exact same state as the previous run, even if the PR labels have changed.

I think the workflow could listen for `on.issues.types['labeled']` events (also applies to pull requests) and automatically start a new run as soon as it's added. Proceeding pushes to the fork will also see the label.

**Comment by olemorud** [comment]
The problem with running on label/comment events is that you can't filter based on specific labels
https://github.com/orgs/community/discussions/26261

When emulating filtering by using a conditional on each job, say by using ...
```yml
if: |
   github.event.action == labeled
&& github.event.label.name == 'clean build'
```
... , adding unrelated labels will still hide the status of the build and instead display a cancelled build. Example:

-----
![image](https://user-images.githubusercontent.com/82065181/220065683-ae946b8a-fcf7-4eee-9d6f-cf52d29111f3.png)

----

Triggering on pull request comments would be even more annoying with this in mind.

I can still open a PR that enables using labels to force clean builds and find a cleaner implementation later. Or we can have the PR authors manually restart the job (e.g. by re-opening the PR) and omit having the build automatically start on added labels
