### ISSUE TITLE
Performance regression with repr for pyroot objects in root 6.28 nightlies.

### ISSUE THREAD

**Issue by scott-snyder** [root-project/root#12817]
Consider this python script:

```
import ROOT
v = ROOT.vector(float)()
for i in range(50000):
    s = repr(v)
    if i%1000 == 0:
        print (i, flush=True)
```

Using ROOT from a dev4 nightly:

/cvmfs/sft-nightlies.cern.ch/lcg/nightlies/dev4/Sat/ROOT/v6-28-00-patches/x86_64-centos7-gcc12-opt

This runs for about 12 minutes and then starts printing errors:

```
21000
cling JIT session error: Cannot allocate memory
Error in Interpreter::toString: the input *((std::string*)0x7ffed5ef1580) = cling::printValue((std::vector<float>*)0x9c5a040); cannot be evaluatedcling JIT session error: Cannot allocate memory
Error in Interpreter::toString: the input *((std::string*)0x7ffed5ef1580) = cling::printValue((std::vector<float>*)0x9c5a040); cannot be evaluatedcling JIT session error: Cannot allocate memory
...
```

Meanwhile, with root 6.26.08:

/cvmfs/atlas-nightlies.cern.ch/repo/sw/master_Athena_x86_64-centos7-gcc11-opt/sw/lcg/releases/LCG_102b_ATLAS_19/ROOT/6.26.08/x86_64-centos7-gcc11-opt

The same script completes normally in about two seconds.

See also ATEAM-885.

**Comment by wlav** [comment]
Odd, as the particular offending code is ancient (2019 or so) and even at the time I disagreed with the implementation and have therefore a different one providing the same functionality in cppyy proper, which you could use as the basis of a fix.

It's a (very) long-standing pet peeve of mine that you can't use Cling to evaluate one-off expressions (not without leaking memory anyway), but the solution is always the same: run the expression in the Python interpreter instead of in Cling, through the bindings. That both prevents the memory leak and gives you typically 4 orders of magnitude in speedup.

**Comment by dpiparo** [comment]
Hello @scott-snyder thanks for reporting and apologies for the late post. I wanted to understand whether the problem the A-Team has is only related to vectors or to a broather set of classes: do you know?
