### ISSUE TITLE
Broken highlighting of tutorials on doxygen

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#12851]
See the attached screenshot for example, from https://root.cern.ch/doc/master/df002__dataModel_8py.html 

![image](https://github.com/root-project/root/assets/15638895/81daf8e2-ac55-45bf-90fb-e6c2b6e04395)

The part within triple quotes `'''` should be considered as a string. Afterwards, the Python code is not highlighted properly etc.

**Comment by couet** [comment]
I’ll look. Thanks

**Comment by couet** [comment]
The code inlining mechanism uses the doxygen command [`\include`](https://www.doxygen.nl/manual/commands.html#cmdinclude). This command does not allow to specify the type of code to be inlined (C++ or python) the only two options available are `doc` and `lineno`. I guess the "code" is considered as C/C++ that's why the highlighting is not correct for that python example. I'll try to find a solution. The simplest would have been an option `.py` like for the `\code` doxygen command (see help). I tried but it does not work.

**Comment by couet** [comment]
This issue is now. fixed by the Doxygen PR: https://github.com/doxygen/doxygen/pull/10077

**Comment by vepadulano** [comment]
That's great, thanks! Any idea on the timeline to the doxygen release with the fix, thus also seeing it fixed on our website?

**Comment by couet** [comment]
I have installed doxygen 1.9.8 (which fixes this issue) on the build machine.
