### ISSUE TITLE
Error in navigation with tessellated volumes

### ISSUE THREAD

**Issue by nicolamori** [root-project/root#13039]
### Check duplicate issues.

- [X] Checked for duplicates

### Describe the bug

The presence of tessellated volumes in the TGeo geometry leads to erroneous node identification from coordinates. The tessellated volume is identified as the node containing the given point, which actually lies in another volume. Removing the tessellated volume the right one is correctly identified.

This issue has originally been reported in the VGM project (see [here](https://github.com/vmc-project/vgm/issues/14#issuecomment-1589757201)) and identified by the VGM developer as a problem with Root navigation. 

### What is the expected behaviour?

The volume including the origin should be found when searching for origin coordinates even with the tessellated tray in the geometry.

### How to reproduce?

A full reproducer is available [here](https://basket.fi.infn.it/f/30bd4036d8/?dl=1). After decompressing the tarball, create the build folder for cmake and build as usual. Then transfer the tray.gdml and vis.mac macros in the build folder and launch the test executable. The test program consists of a GDML tray filled with cubic crystals, and will first show the geometry in an OpenGL canvas, then export the geometry to TGeo and find the volume in the origin (the geometry is also saved in a Root file for convenience). From very last line of the console output one can see that the volume at the origin is the tray, while it should be a cubic crystal. Indeed, commenting out lines 62-64 of main.cpp and running the geometry is now made only of cubes in the very same positions as before, and now TGeo correctly finds a crystal in the origin.

### ROOT version

6.26/04

### How did you install ROOT?

Build from source

### Which operating system are you using?

Archlinux

**Comment by agheata** [comment]
This behaviour is expected since TGeoTessellated does NOT provide navigation functionality on its own, if this is called it just behaves as its bounding box. There is the possibility to convert the geometry in memory to VecGeom as described in this [post](https://root-forum.cern.ch/t/tessellated-volume-behave-like-box-after-transporting-with-geant-3-and-4-after-converting-cad-to-root-geometry/57083) , this requires compiling ROOT with VecGeom support. Summarizing:

- install VecCore with SIMD support:
```
DIR=`pwd` && git clone https://github.com/root-project/veccore.git && mkdir veccore/build && cd veccore/build && cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_VC=ON -DCUDA=ON -DCMAKE_INSTALL_PREFIX=$DIR/veccore_install && make -j install && cd $DIR
```
- install VecGeom:
```
 DIR=`pwd` && git clone https://gitlab.cern.ch/VecGeom/VecGeom.git && mkdir VecGeom/build && cd VecGeom/build && cmake .. -DVECGEOM_BACKEND=vc -DVECGEOM_VECTOR=native -DCMAKE_INSTALL_PREFIX=$DIR/VecGeom_install && make -j install && cd $DIR
```
- configure ROOT to use VecGeom (use the ROOT master which contains some converter and persistency fixes related to this):
```
cmake $ROOT_SOURCE -Dvecgeom=ON -DVecGeom_DIR=<use_above_install_directory>/VecGeom_install
```
- Add the following code AFTER `gGeoManager->CloseGeometry()`:
```
auto converter = TVirtualGeoConverter::Instance(gGeoManager);
   if (!converter) {
      printf("It looks like your ROOT version is missing VecGeom support\n");
   } else {
      converter->ConvertGeometry();
   }
```
- at this point all ROOT shapes will be converted to VecGeom ones, including the tessellated, and the navigation will be dispatched to those.

**Comment by nicolamori** [comment]
Thank you!!
