### ISSUE TITLE
Numerous warnings appear in RooFit due to removed public constructors 

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#13280]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

For my project I use  LCG  nightly builds (dev3 slot) of  ROOT and from this morning I see numerous messages of this kind  

```Warning in <TBufferFile::WriteObjectAny>: since RooNLLVar has no public constructor
	which can be called without argument, objects of this class
	can not be read with the current library. You will need to
	add a default constructor before attempting to read it.
```

### Reproducer

ROOT master from LCG dev3 nightly builds 

### ROOT version

ROOT master from LCG dev3 nightly builds 

### Installation method

LCG dev3 nightly build

### Operating system

centos7 

### Additional context

Same warning  messages I see also for other classes like `RooRealMPFE`

Also I see numerous messages 
```
Warning in <TBufferFile::CheckObject>: reference to object of unavailable class RooAbsArg, offset=983040 pointer will be 0
Error in <TBufferFile::CheckByteCount>: object of class vector<RooAbsArg*> read too few bytes: 227437 instead of 235302
Error in <TClass::New>: cannot create object of class RooNLLVar
Error in <TBufferFile::ReadObject>: could not create object of class RooNLLVar
Error in <TExMap::Remove>: key 463722250 not found at 1407
```
but likely they are induced by the same problem of removed default constructors,

**Comment by guitargeek** [comment]
Hi @VanyaBelyaev, thanks for posting about this!

As explained in [this PR](https://github.com/root-project/root/pull/11909/files) and later also dicussed in [this forum post](https://root-forum.cern.ch/t/retreiving-the-calculation-strategy-of-a-roonll/55715/2), saving test statistics objects to ROOT files like `RooNLLVar` is now prohibited since ROOT 6.28. It only technically seemed to work without error, but in fact the read-back RooNLLVars are corrupted and give wrong results when you read them back even for simple Gaussian cases, as I showed in the description of the linked PR. This and other reasons lead us to the decision to disallow the IO of `RooNLLVar` and other test statistics classes.

From your warnings and error messages, it seems like you're trying to do IO of the RooNLLVar. Is there a way you can avoid this in your workflow? As I said it's not allowed anymore and in older ROOT versions it was not reliable. What people usually do is to save the pdf and the datasets in a RooWorkspace, and maybe a `ModelConfig` to simplify the NLL creation when reading back the data and pdf. Is that not an option for your?

Certainly I was not expecting that the removal of this accidental and buggy IO feature would cause some friction with some users, so I'm happy to help you finding an alternative and better solution!

**Comment by VanyaBelyaev** [comment]
Dear @guitargeek 
Thank you very much for detailed information.
Actually I do no serialize `RooNLLVar` explicitely. 
I have (in python) large shelve-like database, where I store the results of the fits from RooFit - namely `RoofitResult` and `RooPlot` objects.   Probably they "pick-up"  `RooNLLVar` objects indirectly..
For my purposes the deserialized `RooFitResult` and `RooPlot` objects look perfectly OK (however I cannot guarantee that *all* methods for deserialized objects have been tested). 

Actually now within my project  I've provided  the dedicated serializers  ( via `__reduce__` ) for these objects to bypass annoying warning messages, and from  now this issue in not relevant for me anymore.

**Comment by guitargeek** [comment]
Ah I see, so you're serializing a RooPlot, but the RooPlot owns a pointer to the original RooAbsReal that got plotted! But this pointer is not necessary for the content of the plot.

Anyway if you have a solution for now, I'll close the issue. Thanks!
