### ISSUE TITLE
[Math] Vc is not maintained any more: is a migration strategy needed?

### ISSUE THREAD

**Issue by dpiparo** [root-project/root#13713]
### Explain what you would like to see improved and how.

Unfortunately, Vc, a very nice library, is currently not supporting cpp17 and is not supported any more.
On Fedora 36 the compilation of ROOT presents deprecation warnings, but it's just a matter of time before they become errors.
For a particular class of these warnings, i.e. the usage of std::iterator, a PR was proposed to Vc and will be hopefully considered https://github.com/VcDevel/Vc/pull/356 . However, it might be necessary to identify a path to get rid of the dependency on this unsupported product.

### ROOT version

all

### Installation method

all

### Operating system

all

**Comment by bernhardmgruber** [comment]
I have made good experience with the developers of [xsimd](https://github.com/xtensor-stack/xsimd). I have also been using `std::experimental::simd` for a few years, but that is limited to libstdc++. `std::simd` will likely hit C++26, since we finished its design at the last WG21 meeting (see status [here](https://github.com/cplusplus/papers/issues/670)).

**Comment by dpiparo** [comment]
Thanks Bernhard.  I think this can be closed.
