### ISSUE TITLE
Include Tex Gyre Heros in ROOT fonts

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#14064]
### Feature description

The Tex Gyre Heros family of fonts (https://www.gust.org.pl/projects/e-foundry/tex-gyre/heros) is the currently used alternative to the Helvetica fonts as suggested by the newly formed CMS analysis tools documentation website https://cms-analysis.docs.cern.ch/ .

After some investigation, our understanding is that ROOT either tries to display Helvetica (by e.g. asking for it in the preamble of a PDF image) or falls back to a FreeSans font when that's not possible (see also https://github.com/root-project/root/pull/14049)

We should evaluate whether we can also ship Tex Gyre Heros to allow the CMS documentation to report the same type of font being used irrespective of the plotting tool used, platform, PDF viewer.

Notably, we need to understand if the licensing is compatible with ours.

FYI @andrzejnovak  @ttedeschi

### Alternatives considered

Keep using the FreeSans font as alternative to Helvetica. But the current setup means that e.g. the font displayed in a TCanvas might be different from the font displayed in a PDF viewer on the *same* machine if that PDF viewer cannot display Helvetica.

**Comment by couet** [comment]
The ROOT PostScript and PDF backends use the original PostScript-defined 13 font styles which form 4 type families:

[Courier](https://en.wikipedia.org/wiki/Courier_(typeface)) (Regular, Oblique, Bold, Bold Oblique)
[Helvetica](https://en.wikipedia.org/wiki/Helvetica) (Regular, Oblique, Bold, Bold Oblique)
[Times](https://en.wikipedia.org/wiki/Times_Roman) (Roman, Italic, Bold, Bold Italic)
[Symbol](https://en.wikipedia.org/wiki/Symbol_(typeface))

See the "Core Font Set" section in [this document](https://en.wikipedia.org/wiki/PostScript_fonts). These fonts are always available and do not need to be loaded in the PS or PDF file which allows to keep the files' sizes small **which is very important regarding the huge number of such files generated in HEP**. 

So Helvetica is there. There are no license issues for PS and PDF. Unlike the `otf` and `ttf` files used for screen rendering. That's the reason why FreeSans was chosen because it is very similar to Helvetica (on my Mac I could not see the difference)

We can replace the current FreeSan family by "Tex Gyre Heros" but that will be on screen only and will not affect the PDF and PS output. Therefore is it really worth it?

**Comment by couet** [comment]
PR here https://github.com/root-project/root/pull/14841
