### ISSUE TITLE
cmake find_package ROOT 6.30 broken: it requires nlohmann-json

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#14188]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

@bellenot @linev, this was seen by several users: 
https://github.com/root-project/root/issues/14163
https://github.com/root-project/root-docker/issues/60

```
CMake Error at /usr/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
  By not providing "Findnlohmann_json.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "nlohmann_json", but CMake did not find one.

  Could not find a package configuration file provided by "nlohmann_json"
  (requested version 3.10.5) with any of the following names:

    nlohmann_jsonConfig.cmake
    nlohmann_json-config.cmake

  Add the installation prefix of "nlohmann_json" to CMAKE_PREFIX_PATH or set
  "nlohmann_json_DIR" to a directory containing one of the above files.  If
  "nlohmann_json" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /tmp/newroot/cmake/ROOTConfig.cmake:122 (find_dependency)
  gui/CMakeLists.txt:28 (find_package)
```

`builtin_nlohmann` is off in the binary release, so the Findpackage CMake script should not require it to be found.

### Reproducer

```
cmake_minimum_required(VERSION 3.25)

project(ProjectName)

find_package(ROOT 6.30 CONFIG REQUIRED)
```

### ROOT version

```
 ------------------------------------------------------------------
 | Welcome to ROOT 6.30/02                        https://root.cern |
 | (c) 1995-2023, The ROOT Team; conception: R. Brun, F. Rademakers |
 | Built for linuxx8664gcc on Nov 27 2023, 19:50:38                 |
 | From tags/v6-30-02@                                              |
 | With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0                   |
 | Try '.help'/'.?', '.demo', '.license', '.credits', '.quit'/'.q'  |
  ------------------------------------------------------------------
```

### Installation method

Binary Release

### Operating system

Ubuntu 22.04

### Additional context

https://github.com/root-project/root/pull/14178#discussion_r1415435156

**Comment by linev** [comment]
> builtin_nlohmann is off in the binary release, so the Findpackage CMake script should not require it to be found.

Is binary release build with system-provided `nlohmann_json`?
Should one add it to docker as requirement?

**Comment by linev** [comment]
Reason why it searched - it uses in public interfaces in following libraries:
* `ROOTEve`,
*  `RooFitJSONInterface`
*  `RooFitMultiProcess`

Without external `nlohmann_json` is not possible to link with these libraries. 
If ROOT build with external `nlohmann_json`, such external `nlohmann_json` must be provided.

**Comment by ferdymercury** [comment]
> Without external `nlohmann_json` is not possible to link with these libraries.

I see, thanks for the explanation. So from my point of view, either builtin should be turned always to ON as before for binary releases, or the cmake find-script should only require it if ROOTEve is linked, or the requirement for external installation should be added to the dependencies website.

**Comment by linev** [comment]
> cmake find-script should only require it if ROOTEve is linked,

I have no good idea how to implement this in ROOT itself.
It only can be done in users cmake files - who knows which libraries are linked.

But again - if ROOT build with external `nlohmann_json` - it should be provided before ROOT binary can be installed.

**Comment by krasznaa** [comment]
I don't really understand your question. 😕

[tutorials/eve7/boxset.C](https://github.com/root-project/root/blob/master/tutorials/eve7/boxset.C) doesn't seem to need `nlohmann/json.hpp`, does it?

The nlohmann_json "library" is a pure header "library". It does not need to be distributed with the ROOT binaries for those binaries to be functional. All the symbols from `nlohmann/json.hpp` are compiled into the ROOT binaries themselves. 🤔

You "only" need `nlohmann/json.hpp` when using a ROOT header in your own build that itself publicly uses `nlohmann/json.hpp`. For that you do need that actual header.

So I'm still pretty convinced that this is a relatively simple mistake. The machine on which 6.30 was built, probably had nlohmann_json installed on it recently. And people doing the ROOT binary builds didn't notice that their build now picked up nlohmann_json from the system.

This does shine light on a deeper issue though. 😦 The ROOT CMake configuration is a bit too autonomous for my liking. 😦 It will too easily turn features on/off based on what it finds. Instead of asking the user explicitly to specify what they want to have on or off. If it was up to me, I'd remove most of the automation in how the build figures out what it should do, and rather introduce a bunch of [CMake presets](https://cmake.org/cmake/help/latest/manual/cmake-presets.7.html) to ease the life of the users a little.

For the latter, we're using those pretty happily in this project for instance:
  - https://github.com/acts-project/algebra-plugins/
  - https://github.com/acts-project/algebra-plugins/blob/main/CMakePresets.json

Yes, ROOT has a lot more externals than we have in that particular project, but the spaghetti code used for figuring out what would come from where, and what would be turned on or off is also not a great solution. 😦

**Comment by ferdymercury** [comment]
> root tutorials/eve7/event_demo.C+

Looks good.
```

EVEMNG ............. streaming the world scene.
   sending json, len = 6535
   for now assume world-scene has no render data, binary-size=0

EVEMNG ............. streaming scene  [Geometry scene]
   sending json, len = 749
   sending binary, len = 5832

EVEMNG ............. streaming scene  [Event scene]
   sending json, len = 16121
   sending binary, len = 10688


```

**Comment by ferdymercury** [comment]
> I don't really understand your question. 😕
> 

Thanks for the explanation.
My question was: is it possible to modify the ROOT-cmake-find script, so that it only forces the nlohmann-json-dependency if you are going to use ROOT7 classes? So to say, that depending on the `REQUIRED COMPONENTS` that you use in the `find_package` statement, it is more or less 'requiring'.

**Comment by linev** [comment]
Actually, we do not have example with REve code where `nlohmann::json` interface is used.
In the `REveElement.hxx` header file I see such construct:
```
#if __has_include(<nlohmann/json_fwd.hpp>)
#include <nlohmann/json_fwd.hpp>
#else
// This forward declaration works for versions before 3.11.0, which introduced
// a "versioned, ABI-tagged inline namespace". The json_fwd.hpp header is
// present in multi-header installations (the default as of version 3.11.0), and
// single-header installations of version 3.11.2+.
```

Means it can compile macro - as long as json interface is not really involved. 
But will fail if one has to use it

**Comment by krasznaa** [comment]
> My question was: is it possible to modify the ROOT-cmake-find script, so that it only forces the nlohmann-json-dependency if you are going to use ROOT7 classes? So to say, that depending on the `REQUIRED COMPONENTS` that you use in the `find_package` statement in your user code, it is more or less 'requiring'.

That's an interesting question. 🤔 CMake project's can't easily do this. I mean, nothing is impossible, but it's not simple to do.

As long as externals are handled through imported library targets (which I'm not sure the nlohmann_json dependency is used with 😕), one would need to tweak the behaviour of CMake in a pretty fundamental way for this. 🤔 You see, when you tell in (in this case) ROOT's build that library `Foo` needs to publicly link against library `Bar::bar`, CMake exports this information in the `ROOTConfig-targets.cmake` file. (That is a file generated fully by CMake itself.) It will say that `Foo` depends on `Bar::bar`. So at that point `ROOTConfig.cmake` has to produce `Bar::bar` in some way. Even if the user's code itself never wants to use the `Foo` library. Because CMake will not like it that it has the `Foo` library defined (even if unused by others), without all of its requirements met.

So even if `ROOTConfig.cmake` itself doesn't look for nlohmann_json, if any of the CMake code depends on the `nlhmann::json` target (yes, there is such a target in CMake 😄), the CMake configuration would still fail. With a complaint about `nlohmann::json` not being known. 😦

So generally, projects that publicly depend on something else, always look for all of those dependencies with [find_dependency(...)](https://cmake.org/cmake/help/latest/module/CMakeFindDependencyMacro.html). Regardless of which parts of the project the user wants to use. 🤔

**Comment by ferdymercury** [comment]
Thanks!
So I guess the easiest solution would be to add nlohmann-json to https://root.cern/install/dependencies/ and we're all set.

**Comment by linev** [comment]
I propose PR https://github.com/root-project/root/pull/14192

@ferdymercury  You can try it - just modifying `ROOTConfig.cmake` by hand.

**Comment by guitargeek** [comment]
> Reason why it searched - it uses in public interfaces in following libraries:
> 
>     * `ROOTEve`,
> 
>     * `RooFitJSONInterface`
> 
>     * `RooFitMultiProcess`
> 
> 
> Without external `nlohmann_json` is not possible to link with these libraries. If ROOT build with external `nlohmann_json`, such external `nlohmann_json` must be provided.

Note that after https://github.com/root-project/root/pull/14266, this is not true anymore since `ROOTEve` is the only library that still publicly depends on nlohmann-json.

**Comment by linev** [comment]
Thanks Jonas!

I can adjust PR and keep only ROOTEve there.
