### ISSUE TITLE
[RF] RDataFrameToRooFit - Clarification on returned object

### ISSUE THREAD

**Issue by jpherdi** [root-project/root#14329]
### Explain what you would like to see improved and how.

In the tutorial [rf408__RDataFrameToRooFit_8py](https://root.cern.ch/doc/master/rf408__RDataFrameToRooFit_8py.html) the objects `rooDataSet` and `rooDataHist` are not what their name suggests. In reality these objects are only `ROOT.RDF.RResultPtr`.
The real object, which one actually needs to use in something like `RooFit`s `pdf.fitTo(rooDataSet.GetValue())` function can be only called with the method `GetValue()` following the tutorial.
It would be great if that could be clarified as I was very confused by this.
Cheers!

### ROOT version

6.30/02

### Installation method

mamba

### Operating system

Ubuntu 20.04 LTS

**Comment by guitargeek** [comment]
Hi @jpherdi, thanks for the report! I suggest the following changes to the tutorials:
https://github.com/root-project/root/pull/14332

Would this address this issue?

Also, note that the RooFit RDF helpers are not feature complete yet:
https://github.com/root-project/root/issues/7223

I didn't continue working on this, because it was not clear to me which features would actually get used by the users.

If it's missing something that you need, for example the treatment of weight columns, please comment on the other issue I linked so we can give it higher priority.
