### ISSUE TITLE
new PyROOT/cppyy fails to pickle enums

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#15104]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

I am using ROOT 6.31/01 from LCG dev3 cvmfs nightly build.
and I've observed that for new PyROOT/cppyy  at leats some enum objects 
are not pickleable anymore 

### Reproducer

Reproducer is very trivial
```python
import ROOT,pickle

print ( 'ROOT version %s' % ROOT.gROOT.GetVersion() )

a = ROOT.TMVA.Types.kBDT
print ( 'enum:', a )

## error here:
pickle.dumps  ( a )
```

### ROOT version

6.31/01 from the LCG dev3 cvmfs nightly build 
 

### Installation method

LCG dev3 cvmfs nightly build 

### Operating system

Linux

**Comment by guitargeek** [comment]
Thanks for reporting! This seems to be a limitation with the new cppyy, because enums are correctly typed now instead of converting them always to `int`. You can see the same behavior in vanilla cppyy:

```python
import cppyy
import pickle

cppyy.cppdef("""
enum MyEnum { Foo, Bar };
""")

a = cppyy.gbl.Foo

pickle.dumps(a)
```
```txt
Traceback (most recent call last):
  File "/home/jonas/tmp/enums.py", line 10, in <module>
    pickle.dumps(a)
_pickle.PicklingError: Can't pickle <class '__main__.MyEnum'>: attribute lookup MyEnum on __main__ failed
```

A backwards compatible workaround would be to cast to int explicitly, like:
```python
a = int(ROOT.TMVA.Types.kBDT)
```
Would that be okay for you, or are these changes to your code not sustainable?

**Comment by VanyaBelyaev** [comment]
Hi Jonas,
I've used this patch (explicit conversion to int) for my code and 
it is a kind of patched solution.
But it will be nice (for future) of a proper fix appear in cppyy.
(Actually location of this bug.feature was a rather tricky - 
it happens when I make parallelisation of 
my task into several processors/nodes using parallel python.
For technical reasons the output is suppressed   in a very harsh way, 
therefore the final "visible" error report has nothing to to
 with pickling on enums.. And it takes some time to identify the plroblem.
Temporary patch in my code ok, but proper long-term  solution 
 is better. For a time being it is OK for me. .

**Comment by guitargeek** [comment]
Thanks a lot for your reply! Ok, in that case we'll think about how this can be supported again.

@wlav, it would also be interesting to hear your opinion here, since typing the enums not as `int` anymore was apparently a deliberate choice by cppyy in the recent years.

**Comment by wlav** [comment]
Mapping enums to Python `int` breaks templates, hence each `enum` type is now an actual type. Fix would be to make these pickle-able, rather than regressing.

I'm surprised that `pickle` is looking for `__main__.MyEnum` and not `cppyy.gbl.MyEnum`, though, which is probably b/c the generated `enum` types do not have a `__module__` attributed pointing back at `cppyy.gbl` or whatever which relevant namespace.

**Comment by wlav** [comment]
Yes, adding `__module__` is all there's to it.

**Comment by guitargeek** [comment]
> Yes, adding `__module__` is all there's to it.

Thanks for the investigation @wlav! Are you fixing this in cppyy yourself, or should I make a PR there?

**Comment by wlav** [comment]
https://github.com/wlav/CPyCppyy/commit/fbbca90e1b9b299ea042229d93723dc1b03bf1ec

**Comment by wlav** [comment]
Same would fail for any subclass then.

Seems that renaming the `enum` Python-side from `MyEnum` to `MyClass.MyEnum` (such that `__name__` becomes `"MyClass.MyEnum"`) and removing `MyClass` from `__module__` fixes the issue, but the former doesn't feel right.
