### ISSUE TITLE
[ci] clang-format fails when adding commits

### ISSUE THREAD

**Issue by jblomer** [root-project/root#15107]
### Check duplicate issues.

- [X] Checked for duplicates

### Description

When adding a commit to a PR, the rerun of clang-format fails with an output like the following

```
+ echo 'Running clang-format against branch master, with hash 60f72758eafe149ffba9bc6d3742eb10cc8d892d'
Running clang-format against branch master, with hash 60f72758eafe149ffba9bc6d3742eb10cc8d892d
++ git diff --name-status 60f72758eafe149ffba9bc6d3742eb10cc8d892d
++ grep -i -v LinkDef
++ sed -E 's,^.[[:space:]]+,,'
++ grep -v -E '^D +'
fatal: bad object 60f72758eafe149ffba9bc6d3742eb10cc8d892d
+ COMMIT_FILES=
+++ which clang-format
++ git-clang-format --commit 60f72758eafe149ffba9bc6d3742eb10cc8d892d --diff --binary /usr/bin/clang-format
fatal: bad object 60f72758eafe149ffba9bc6d3742eb10cc8d892d
+ RESULT_OUTPUT=
```

### Reproducer

Submit a PR, add a commit to it.

### ROOT version

master

### Installation method

n/a

### Operating system

n/a

**Comment by hahnjo** [comment]
I think the issue is that `.github/workflows/code_analysis.yml` fetches `${{github.base_ref}}`, which is the symbolic name and may not actually be identical `${{ github.event.pull_request.base.sha }}`. I've been able to reproduce this in https://github.com/root-project/root/pull/15172 by adding a new commit, but force-pushing (for example when amending a commit) always updates the base sha for me, so the problem doesn't trigger. Now I need to wait for a new commit in `master` to test my fix...
