### ISSUE TITLE
[PyROOT] Example with inheriting from `ROOT.Math.IMultiGenFunction` doesn't work after recent cppyy upgrade

### ISSUE THREAD

**Issue by guitargeek** [root-project/root#15315]
### Description

One example from the ROOT manual doesn't work anymore with ROOT 6.32:
https://root.cern/manual/python/#alternative-for-tpymultigenfunction-and-tpymultigradfunction

```Python
import ROOT

from array import array

class MyMultiGenFCN( ROOT.Math.IMultiGenFunction ):
    def NDim( self ):
        return 1

    def DoEval( self, x ):
        return (x[0] - 42) * (x[0] - 42)

    def Clone( self ):
        x = MyMultiGenFCN()
        ROOT.SetOwnership(x, False)
        return x

def main():
    fitter = ROOT.Fit.Fitter()
    myMultiGenFCN = MyMultiGenFCN()
    params = array('d', [1.])
    fitter.FitFCN(myMultiGenFCN, params)
    fitter.Result().Print(ROOT.std.cout, True)

if __name__ == '__main__':
    main()
```
The error is:
```txt
input_line_33:38:23: error: expected '(' for function-style cast or type construction
      return unsigned int{};
             ~~~~~~~~ ^
Traceback (most recent call last):
  File "/home/rembserj/example.py", line 5, in <module>
    class MyMultiGenFCN( ROOT.Math.IMultiGenFunction ):
TypeError: no python-side overrides supported (failed to compile the dispatcher code)
```

See:
  * https://root.cern/manual/python/#alternative-for-tpymultigenfunction-and-tpymultigradfunction
  * https://root-forum.cern.ch/t/minuit2minimizer-with-root-math-imultigenfunction/59102

**Comment by aaronj0** [comment]
For the `IMultiGenFunction` crossinheritance I see that we inject the`NDim()` method into the dispatched code:

``` unsigned int NDim() const {
    PyObject* iself = (PyObject*)_internal_self;
    if (!iself || iself == Py_None) {
      PyErr_Warn(PyExc_RuntimeWarning, (char*)"Call attempted on deleted python-side proxy");
      return unsigned int{};
    }
```
using this code block:

https://github.com/root-project/root/blob/0aa2b6b8760b78dff2cffd873f955735fa1b0ef3/bindings/pyroot/cppyy/CPyCppyy/src/Dispatcher.cxx#L41-L51

Cling fails to compile the initialization in `return unsigned int{};` since it is not valid C++.  We should also consider `unsigned int` and other multi keyword types that require a function style cast for value initialization (like `return (unsigned int){}`. If I am not wrong this should just work for all primitives(as zero initialization) and user-defined types(as default initialization).

I was able to get this example from the manual to work with this fix. Based on the issue, I was of the opinion we should land this upstream but I see that this is a high priority issue and @wlav is on vacation.  

What do you think @guitargeek @dpiparo
