### ISSUE TITLE
[PyROOT] TProfile2D::Fill ambiguities preventing use of some signatures in pyROOT

### ISSUE THREAD

**Issue by will-cern** [root-project/root#15688]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

It appears that some member function ambiguities prevent pyROOT from calling the proper function. This has been encountered specifically with TProfile2D with the Fill method (see reproducer below). 
The equivalent code runs fine in C++.

### Reproducer

import ROOT
h = ROOT.TProfile2D("h","h",1,0,1,1,0,1)
h.Fill("a","b",1,1)

Produces this error:

```
input_line_40:8:47: error: call to member function 'Fill' is ambiguous
         new (ret) (int) (((TProfile2D*)obj)->Fill(*(const char**)args[0], *(const char**)args[1],
```

### ROOT version

master, 6.32

### Installation method

pre-built

### Operating system

any

**Comment by guitargeek** [comment]
We're talking about this TProfile2D method here:
```c++
virtual Int_t     Fill(const char *namex, const char *namey, Double_t z, Double_t w = 1.);
```
That is a bit nasty, because actually it declares two different signatures, one with the optional parameter and one without.

In case of no optional `w` parameter, it would theoretically `override` the `TH2::Fill(x, y, w)` method, but does it really? I don't even know how C++ works here, I got to try this out. But it's no surprise that cppyy also gets confused.

Reference:
https://root.cern.ch/doc/master/classTH2.html#a368290c4a1b084eaf7b581f49647e04d
https://root.cern.ch/doc/master/classTProfile2D.html#af69e7c22659b8cfc8d5033ce3af1080d

**Comment by guitargeek** [comment]
Ok, I tried to reproduce the situation with a simple C++ example:
```
#include <iostream>
#include <string>
#include <memory>

struct A {
   virtual std::string func() { return "A"; }
};

struct B : public A {
   std::string func() { return "B"; }
   std::string func(int) { return "B"; }
};

struct C : public A {
   std::string func(int=0) { return "C"; }
};

int main() {

   std::unique_ptr<A> a = std::make_unique<A>();
   std::unique_ptr<A> b = std::make_unique<B>();
   std::unique_ptr<A> c = std::make_unique<C>();

   std::cout << a->func() << std::endl;
   std::cout << b->func() << std::endl;
   std::cout << c->func() << std::endl;
}
```
Output:
```txt
A
B
A
```
Interesting. So if you have a method with default parameters, and the signature with the implicit defaults seems to override a base class method, it actually doesn't. So this is a bug in TProfile2D that needs to be fixed:

https://github.com/root-project/root/pull/15693
