### ISSUE TITLE
root-framework snap for Ubuntu missing wayland support

### ISSUE THREAD

**Issue by wofr06** [root-project/root#15723]
### Check duplicate issues.

- [x] Checked for duplicates

### Description

When using root under Ubuntu 24_04 and the wayland graphics then graphical output is not possible. Only after xhost + a command like root -a is working properly.
It looks as if in the snap.yaml in the plug section wayland is missing

### Reproducer

start a session under Ubuntu using Wayland, not X11.
root -a will not show the splash screen
workaround: issue xhost +

### ROOT version

snap-id:      XSlaE4S2cu0h5r6o7dFaFiQIsugKLFpa
tracking:     latest/stable
refresh-date: vor 8 Tagen, um 12:59 CEST
channels:
  latest/stable:    v6-30-04 2024-02-03 (931) 1GB -
 

### Installation method

snap

### Operating system

Ubuntu 24.04

**Comment by guitargeek** [comment]
One more reason to remove the splash screen:
   * https://github.com/root-project/root/pull/15056

**Comment by guitargeek** [comment]
Hi, thanks for your comment! I didn't misunderstand the problem, I just made a fly-by comment about the obvious point before coming back it. Sorry for that! I was abusing your post to lobby for the removal of the splash screen that I proposed.

The ROOT developers were anticipating this situation and developed a new platform-independent web-based graphics stack, which will replace the default way of how plots and histograms are shown. I don't think it is enabled by default in any ROOT release yet, but it would be very interesting to know if it works also in the context of the root-framework snap! Have you tried with ROOT `master`, where the web graphics is the default?

@linev, what would be your recommendation? Maybe we can make web graphics the default for wayland?

**Comment by dpiparo** [comment]
Hi @wofr06 ,
Thanks for reporting this and for mentioning the `xhost` workaround.
As said above, version 6.32.00 provide as an opt-in a novel version of the graphics and GUIs, based on web browsers for the rendering. While the `TBrowser` visualisation is to be considered basically production-level, the new web-based graphics still misses some functionality - however, it is quite advanced and could be indeed a solution for you. 
In order to activate it you can:
- start ROOT with the `root --web` command
- invoke programmatically `gROOT->SetWebDisplay()` at the startup of your program
- add the line `Canvas.Name: TWebCanvas` to the `.rootrc` file (which can be in your home directory, a bit like `.bashrc` or similar)
ROOT also has a new `TBrowser`, as mentioned above, `ROOT::RBrowser` which is web based.

In case you are interested to try, we are very interested in your feedback!

**Comment by linev** [comment]
> Maybe we can make web graphics the default for wayland?

Do we have method to detect `wayland`? 
In general our plans to make web gui default starting from the next release.

**Comment by wofr06** [comment]
The proposed root --web does not help, I am getting as before
Authorization required, but no authorization protocol specified
when using the snap. I am not sure but it looks as if there is missing just one line in the snap.yaml.It is located in  /snap/root-framework/current/meta/snap.yaml after installation. Instead of

> plugs:
>   home: null
>   network: null
>   opengl: null
>   x11: null
>   desktop: null
>   desktop-legacy: null
>   removable-media: null
>   shared-memory:
>     private: true
> layout:

you probably have to add 
>  wayland:null

in the plugs section when building the snap. But I am not sure, as I dont build snaps myself.

**Comment by linev** [comment]
You can try `root --web=server:7788`. 

Then try to create canvas - message should appear with URL which can be copied in the web browser.

Do not use `-a` flag - it still requires normal X11.

**Comment by wofr06** [comment]
Ok, I was just missing the `gROOT->SetWebDisplay()` line. Now it works and even looks better than with the X11/Wayland graphics.

**Comment by dpiparo** [comment]
I am closing the issue since X11 can be invoked as well as the webgraphics .
