### ISSUE TITLE
[RF] Support for setData method in new EvalBackend classes

### ISSUE THREAD

**Issue by will-cern** [root-project/root#15763]
### Feature description

The legacy backend classes, inheriting from, `RooAbsTestStatistic`, implement the `RooAbsReal::setData` method that allows for datasets to be swapped over in a test statistic function without having to reconstruct the test statistic. To support the new backend, in xRooFit I am having to destroy and recreate the test statistics (NLL function) each time I change the dataset. I dont know if this introduces an unnecessary overhead or not, but I'd be interested to know if implementing the `setData` method with the new classes could be easily implemented or not?

**Comment by guitargeek** [comment]
Hi @will-cern, thanks for the report!

I'm a bit surprised by this, because `setData()` on the new likelihoods should already work. I have added a test to also cover this now: https://github.com/root-project/root/pull/16353

But maybe there is a corner case where it doesn't work? Does it have to do something with the global observables in data? For these we have already great test coverage by the way:
https://github.com/root-project/root/blob/master/roofit/roofitcore/test/testGlobalObservables.cxx#L371

I know that data resetting is a bit fragile with the *old* NLL (`EvalBackend("legacy")`). Maybe you're doing some workarounds that make it work in that case, but this work around is not applicable to the new NLL where a simple `setData()` call should suffice?

Anyway, please let me know how I can reproduce the issue if it's really there!

**Comment by guitargeek** [comment]
I closed this issue because as far as I know, this is already implemented. Please reopen a new issue with a precise reproducer in case you should still encounter a problem with `setData()`. Thanks a lot!
