### ISSUE TITLE
[geom] Potential typo in function name case: DistanceToPrimitive

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#16087]
### Check duplicate issues.

- [ ] Checked for duplicates

### Description

There are a couple of places in ROOT that use a different case for one of the functions derived from TObject. I was wondering if it's a typo, or if it's on purpose to not override it. If it's a typo, maybe a new function could be added with the right name, and keep the old signature as an alias to the correct one.

`DistancetoPrimitive` vs `DistanceToPrimitive`

```
/opt/root_src/documentation/users-guide/WritingGUI.md:2603:`DistanceToPrimitive()` that computes a ‘‘distance'' to an object from
/opt/root_src/documentation/users-guide/Graphics.md:265:The second one is `DistanceToPrimitive(px,py)`. This function computes a
/opt/root_src/documentation/users-guide/Graphics.md:527:as `DistanceToPrimitive()` and `ExecuteEvent()`. Its primary use is for
/opt/root_src/geom/geom/src/TGeoBoolNode.cxx:607:Int_t TGeoUnion::DistanceToPrimitive(Int_t /*px*/, Int_t /*py*/)
/opt/root_src/geom/geom/src/TGeoBoolNode.cxx:1031:Int_t TGeoSubtraction::DistanceToPrimitive(Int_t /*px*/, Int_t /*py*/)
/opt/root_src/geom/geom/src/TGeoBoolNode.cxx:1464:Int_t TGeoIntersection::DistanceToPrimitive(Int_t /*px*/, Int_t /*py*/)
/opt/root_src/geom/geom/inc/TGeoBoolNode.h:69:   virtual Int_t DistanceToPrimitive(Int_t px, Int_t py) = 0;
/opt/root_src/geom/geom/inc/TGeoBoolNode.h:113:   Int_t DistanceToPrimitive(Int_t px, Int_t py) override;
/opt/root_src/geom/geom/inc/TGeoBoolNode.h:151:   Int_t DistanceToPrimitive(Int_t px, Int_t py) override;
/opt/root_src/geom/geom/inc/TGeoBoolNode.h:188:   Int_t DistanceToPrimitive(Int_t px, Int_t py) override;
/opt/root_src/gui/ged/doc/index.md:32:`DistanceToPrimitive()` that computes a ‘‘distance'' to an object from
/opt/root_src/hist/doc/v530/index.html:136:  <li>Update in the class by implementing <tt>DistanceToPrimitive</tt> and <tt>ExecuteEvent</tt>. This allows the
```

### Reproducer

`grep -n -r DistanceToPrimitive /opt/root_src/*`

### ROOT version

```
ROOT v6.32.00
Built for linuxx8664gcc on May 28 2024, 05:02:02
From tags/v6-32-00@v6-32-00
With c++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Binary directory: /opt/root/bin
```

**Comment by couet** [comment]
Good catch! indeed the real one is DistancetoPtrimitve (small t). The ones with capital T  in the index file are typos I guess. In particular in the old User guide. I guess we can leave it as this guide is obsolete now and not updated anymore. Those with capital T in the TGeo code are more suspect I guess @agheata should have a look.

**Comment by couet** [comment]
I made a PR for the non-geom occurrences: https://github.com/root-project/root/pull/16088
I let @agheata comment on the geom ones.

**Comment by dpiparo** [comment]
I agree with @couet . It should be rather easy for @agheata to figure out what's going on. Thanks for the catch, @ferdymercury !

**Comment by agheata** [comment]
`DistancetoPrimitive` is the base method to be overridden by visual primitives attached to the pad. In `geom` we attach several different objects. Among these, shapes implement this function directly, while for volumes there is some traversal logic in the geometry painter, dispatching eventually to the shapes methods. Composite Boolean shapes are special and need an extra internal specialized dispatching for union, intersection, and subtraction. The intention was to do this dispatching by avoiding the TObject interface (Boolean nodes are never added directly to the pad), and this is why the upper case `T`. However, due to the complexity, these functions are not implemented, so now they are not even connected to `TGeoCompositeShape::DistancetoPrimitive`. 

Sorry for this long explanation, this is only to say there is nothing to worry about, the functions are placeholders to remember that this functionality could be added at some point. I would close this issue.
