### ISSUE TITLE
Doc for `RInterface::Take` isn't clear about `column` parameter

### ISSUE THREAD

**Issue by Axel-Naumann** [root-project/root#16487]
### Explain what you would like to see improved and how.

https://root.cern/doc/master/classROOT_1_1RDF_1_1RInterface.html#aa571f08b8e4d9300cacdea039a379a22

`column` has a default value, but the doc doesn't say what it will do if I don't pass a value. Is that totally obvious and I'm just missing this, or is it documented elsewhere?

### ROOT version

master

### Installation method

n/a

### Operating system

n/a

**Comment by martamaja10** [comment]
Hi @Axel-Naumann, this is not directly documented at action Take but there is an explanation what happens when you use DefaultColumns here: https://root.cern/doc/master/classROOT_1_1RDataFrame.html#default-branches . With Take, it will be analogous to the `Histo1D()` or `Min()` shown in the example code. So `Take<T>("")`  will act on the first of the default columns (you will have to correctly specify the template though, otherwise you'll get an error). I can extend the example to show `Take` as well, would that be a satisfactory solution?
