### ISSUE TITLE
[Hist] TGraph::Sort when already sorted

### ISSUE THREAD

**Issue by PhilipHB** [root-project/root#6352]
Currently, `TGraph::Sort` does not check if the data is already sorted (stored in bit `TGraph::kIsSortedX`). For the implemented quicksort, sorting already sorted data is the worst case performance scenario, so I believe a check would be helpful.
Since the user can supply a custom `greaterfunc`,  a check similar to https://github.com/root-project/root/blob/1dba738f4e5c472d7b6777da49e00ef041696dba/hist/hist/src/TGraph.cxx#L2394 might be appropriate.

**Comment by guitargeek** [comment]
Hi @vepadulano, since you worked on #13632, which touches the same code, can you maybe comment on this issue? Maybe After the updates by @siliataider, this problem has "sorted" out itself?

**Comment by vepadulano** [comment]
After the patch of the linked PR, the `TGraph::Sort` method now forwards to `std::stable_sort` (probably in the future `std::sort` as soon as we are sure we can use a working libc++ implementation). So the worst case performance scenario mentioned in the issue is not possible anymore, since the standard implementers use a merge sort algorithm for `std::stable_sort`, this issue can be closed
