### ISSUE TITLE
PyROOT:  virtual  C++ method overriden in python  ignored with  further inheritance chain  

### ISSUE THREAD

**Issue by VanyaBelyaev** [root-project/root#6470]
## Describe the bug

The virtual C++ methods overriden in some python class is ignored in the subsequent subclass. 

Simple examples is given in [here] (https://gist.github.com/VanyaBelyaev/fb58efd76b693a7777c9c83a6f43ae15)
In short:
 - C++ class A, 
 -  python class B, that inherits from   A  and override virtual method from A 
 -  python class C, that inherits from B  and override (the same) virual method  form A (and B)
 -  python class D, that inherits from B and has empty body  

And f one   call the method from A,  B, C , D 
 - for A one gets original        C++ behaviour  (OK)
 - for B one gets the overriden behaviour  (OK)
 - for C one gets overriden behaviour defined in C (OK)
 - for D one gets the     original C++ behaviour (  that is not OK) 

## Expected behavior

It is expected that    D  picks up   the overriden method from class B,   as naturally  expected for the inheritance pattern  

## To Reproduce

Simple gist is [here] (https://gist.github.com/VanyaBelyaev/fb58efd76b693a7777c9c83a6f43ae15)

## Setup

1. ROOT version   623/01
2. Operating system  CentOS7, lxplus x86, 64-centos7-gcc9-opt

3. How you obtained ROOT:  `dev3/latest`  nightly LCG  slot,

**Comment by etejedor** [comment]
Thank you for the complete report! I confirm I can reproduce with current master.

**Comment by etejedor** [comment]
The reason for this behaviour seems to be that all the Python classes in the reproducer (`B`, `C` and `D`) get a `Dispatcher` wrapper class automatically created (`Dispatcher1`, `Dispatcher2` and `Dispatcher3`, respectively) that inherits from `A`. Since for `B` and `C` `fun1` is overridden in Python, `Dispatcher1` and `Dispatcher2` define a `fun1` implementation that redirects the call to the Python `fun1` of `B` and `C`, respectively. That is not the case of `D`, whose `Dispatcher3` defines no `fun1`.

What I described above explains the behaviour reported in this ticket. When calling `d.fun2()`, which in turn calls `fun1`, the latter will be resolved to `A::fun1`, whereas one would expect that it is the `fun1` defined in Python by `B` that is called instead.

This issue does not exist in upstream cppyy: `Dispatcher3` inherits from `Dispatcher1` (`B`'s dispatcher) and not from `A` directly, which means that the call to `fun1` from `fun2` will be resolved to `Dispatcher1::fun1`, which will redirect the call to Python (`B`'s `fun1`).

**Comment by Axel-Naumann** [comment]
Hi Vanya, what does this break for LHCb, how critical is this?

**Comment by VanyaBelyaev** [comment]
Dear Axel,
I cannot speak on behalf of LHCb, but it affects my own project  and several current of physics  analyses by our group. It  definitely prevents us from migration to new PyROOT -  without the fix  we are forced to  use  ROOT 6.20. 
Cheers, Vanya
