### ISSUE TITLE
Add posibility to build only the Math libraries

### ISSUE THREAD

**Issue by L0ric0** [root-project/root#6617]
I would like to have a posibility to build only the math libraries or that they are split out from the main project, as we don't want to use root as an application but are writing simulations in c++ and would not like to build our own math lib. 

At the moment it is possible to build the math libs one by one but the c++ interpreter is build as a dependency of them (also some dependency that uses openssl) which is not needed to use the pure math libs. This increases build times unreasonably.

I just build the MathMore target. For this Target about 97% of the compile steps where made up of compiling the interpretor.

**Comment by guitargeek** [comment]
I commented a bit on this on the forum:
https://root-forum.cern.ch/t/suggestions-to-partially-compile-the-math-component-into-julia-jll-library/56485

I think this is not something we can prioritize as ROOT developers, because obviously for ROOT we don't need `mathcore` and `mathmore` standalone.

But for an external contributor who wants to make these standalone builds, this could be a nice project!

**Comment by dpiparo** [comment]
I consider this nice suggestion absorbed in the current effort of the so-called "CMake Superbuilds"
