### ISSUE TITLE
rdf.Snapshot columnList - automate size columns

### ISSUE THREAD

**Issue by andrzejnovak** [root-project/root#6932]
Could `rdf.Snapshot`  figure out which columns it needs for the sizing information and include them automatically? I am assuming since rdf is probably agnostic about the actual branch naming scheme there is some underlying info in the branches that lets rdf identify which one is which anyway (e.g. two different sized collections).

**Comment by eguiraud** [comment]
Fair suggestion, thanks! This is fairly tricky to implement because, in general, we want to know the column types at compile-time, but the information about the type of a potential "size branch" is only known at runtime (i.e. when opening the file). So there is little hope to make this work for `Snapshot<coltype1, coltype2, coltype3>(...)`.

For a just-in-time-compiled call, i.e. `Snapshot(...)`, we could add some logic here: https://github.com/root-project/root/blob/0f364e765bd6eec3f92f4b6983719d53eff00c72/tree/dataframe/inc/ROOT/RDF/RInterface.hxx#L477

to inspect the input columns, and if they are a branch check if they have an associated size branch and also add that one to the column list.

**Comment by eguiraud** [comment]
This is fixed in master and v6-26-00-patches (aka the upcoming v6.26.06) for the case of a jitted Snapshot call (i.e. when no template parameters are specified, so the most common case). @andrzejnovak please let us know if you still have issues with the current master branch or that release.
