### ISSUE TITLE
RooFit for loop fitTo explodes in memory usage

### ISSUE THREAD

**Issue by lan13005** [root-project/root#6975]
- [X] Checked for duplicates

### Describe the bug

Everytime I call fitTo there seems to be various roofit objects that are created and are not cleaned after every iteration. I cannot get RooTrace::dump() to output anything but I am able to use RooTrace::printObjectCounts() to output the object counts. It seems fitTo creates a bunch of RooAbsCollection objects that are not cleaned which starts to consume all the memory. I can see the resident memory usage go up when looking at the top command.

### Expected behavior

Well, ideally, I hope that I would be able to call fitTo all the times I would like

### To Reproduce

I will include it here since it is really short program

```
void test(){

    RooTrace::active(kTRUE);
    RooTrace::mark();
    RooRealVar x("x","x",-10,10);
    RooDataSet d("d","d",RooArgSet(x));
    RooRealVar s("s","s",1,1,10);
    RooRealVar m("m","m",0,-10,10);
    RooGaussian g("gauss","gauss(x,m,s)",x,m,s);
    RooPlot *f=x.frame();
    for (Int_t j=0; j<300; ++j){
        x.setVal(gRandom->Gaus(0,1));
        d.add(x);
    }
    for (Int_t i=0; i<10; i++) {
        cout << "\n------------------------------\nStart iteration " << i << endl;

        cout << "Before fitting" << endl;
        RooTrace::printObjectCounts();

        g.fitTo(d,RooFit::PrintLevel(-1));//,RooFit::SumW2Error(true),RooFit::BatchMode(true));
        cout << "After fitting" << endl;
        RooTrace::printObjectCounts();
     }
}
```

### Setup

Have tried root 6.08/ 6.23 on CentOS 7. Built the root distros

**Comment by guitargeek** [comment]
Hi! The `RooTrace` cannot be used like that, because it doesn't track all the constructors and destructors of RooAbsCollection. If you want to use it, you have to change the code in the classes you want to trace.

Alternatively, you can measure memory consumption with `ProcInfo`, similar to https://github.com/root-project/root/issues/7933:
```C++
#include "RooRealVar.h"
#include "RooGaussian.h"
#include "RooPlot.h"
#include "RooTrace.h"

void test() {

    RooTrace::active(kTRUE);
    RooTrace::mark();
    RooRealVar x("x","x",-10,10);
    RooDataSet d("d","d",RooArgSet(x));
    RooRealVar s("s","s",1,1,10);
    RooRealVar m("m","m",0,-10,10);
    RooGaussian g("gauss","gauss(x,m,s)",x,m,s);
    RooPlot *f=x.frame();

    for (Int_t j=0; j<300; ++j){
        x.setVal(gRandom->Gaus(0,1));
        d.add(x);
    }

    ProcInfo_t pinfo; 

    for (Int_t i=0; i<1000; i++) {

        g.fitTo(d,RooFit::PrintLevel(-1));//,RooFit::SumW2Error(true),RooFit::BatchMode(true));

         gSystem->GetProcInfo(&pinfo);
         std::cout << i << "  memory usage " << pinfo.fMemResident << "  " << pinfo.fMemVirtual << std::endl;
     }
}
```

Now, I don't see any memory increase per fit iteration.

The only thing that happens is that the memory consuption climbs very very slowly when you do tens of thousands of fits because of the MemPoolForRooSets (also reported in https://github.com/root-project/root/issues/7933).

But with the recent changes to the MemPoolForRooSets, this increasing memory consumption is strongly reduced and not relevant in your example.

I will close this issue because it relies on a wrong report based on `RooTrace`, but it you have any more memory issues please feel free to open another thread!

Cheers,
Jonas
