### ISSUE TITLE
Print variable importances for each fold when using Cross Validation

### ISSUE THREAD

**Issue by arvindv92** [root-project/root#7092]
### Is your feature request related to a problem? Please describe.
When TMVA training is run with k-fold cross validation, the variable importances (both method unspecific and method specific) are not printed out by TMVA.

### Describe the solution you'd like
It would be nice if TMVA could print out the variable importances for each fold, as evaluated on the training set for that fold.

### Additional context
I see this issue with ROOT 6.22.06 on lxplus, run by invoking 

```source /cvmfs/sft.cern.ch/lcg/app/releases/ROOT/6.22.06/x86_64-centos7-gcc48-opt/bin/thisroot.sh```

I have tried training both with and without ```FoldFileOutput=True``` in the CrossValidation constructor, and don't see the variable importances in either.

**Comment by guitargeek** [comment]
Thanks for opening this issue!

The training part of TMVA is not developed anymore, that's why this issue was not be addressed. Sorry for not giving any feedback and leaving it in limbo state for so long.

See also: https://indico.cern.ch/event/1356068/contributions/5709442/attachments/2811744/4907885/ML4EP_Feedback.pdf

Quote from slide 4:
> We want to support experiments inference (C++) for cases that are difficult to
implement or require heavy dependencies.
We don’t want to compete with existing industry tools for training.

**Comment by goi42** [comment]
...oh, that really feels like the end of an era. Too bad--I always liked TMVA.
