### ISSUE TITLE
Improvements in TUnuran and ROOT::Math::DistSampler

### ISSUE THREAD

**Issue by lmoneta** [root-project/root#7332]
As requested in https://root-forum.cern.ch/t/can-one-pass-dpdf-to-root-distsampler-for-unuran/43652, it would be nice to have the DistSampler class having th epossibility to pass Derivative of Pdf or CDF. 
In addition it would be nice to pass Unuran methos specific parameters to Unuran methods. Now this is possible only using the string API

**Comment by AntoniMarcinek** [comment]
@lmoneta It would also be nice to use `_chg_truncated` functions to change the range of the sampled numbers without reinitializing the generator. Since there is separate function for each method (fortunately with the same argument list), it seems reasonable to have a function pointer stored in TUnuran, that would be initialized to appropriate function based on the method chosen. For "auto" or methods that have no such capability it would have to be initialized  to a function that throws an exception.

**Comment by AntoniMarcinek** [comment]
@lmoneta Regarding the method parameters, it is fine to pass them through the string API. The point is that this should be clearly documented in `TUnuran` doxygen and for the `TUnuranSampler` doxy it should be mentioned and redirected to `TUnuran` doxy. Right now the information is hidden in tutorials and the code.

I am not sure if there is an elegant way to add methods to `TUnuranSampler`/`TUnuran` that would set the parameters. Maybe something like
```
SetParameter(const TString& name)
SetParameter(const TString& name, const double value)
```
that would build the string passed to the string API when `Init()` is called.

**Comment by AntoniMarcinek** [comment]
Do you have any expectation when this might be delivered?

**Comment by lmoneta** [comment]
Hi, it should be done for 6.26. 
Would you need to have it as soon as possible in the ROOT 
master ?

**Comment by AntoniMarcinek** [comment]
It would be nice to have it in the master soon. Actually I have yet another request: a multidimensional mode (I think I didn't mention it earlier). For now I had to move to the lower level which is not exactly great. To summarize, I ask for the following new features:

1. Set dpdf and cdf
2. Set multidimensional mode `SetMode(const double* mode)`
3. Support for `_chg_truncated`, i.e. range of sampled numbers, which could be narrower than the domain (this needs first support in `TUnuran`, then in the sampler)
4. Documentation of passing method-specific parameters via the string API or even better an interface making it easier to build the respective string (`SetParameter(const std::string& name, const double val)` and similar methods for other types of parameters)

**Comment by AntoniMarcinek** [comment]
@lmoneta Actually out of the above the most pressing is `SetMode(const double* mode)`, because this is the only one for which I don't have a workaround (I need to use `DistSampler` not `TUnuran` in the respective code). I can provide a pull request with mode data member being a `std::vector<double>` and `SetMode(const double mode)` setting a single entry and both 1D and ND setters clearing any previous entries. Should I provide the PR or do you prefer to implement it yourself (I guess this is faster than actual review of the PR and merging)?

**Comment by lmoneta** [comment]
Thank you for the feedback. I 'll try to implement something in the next days and open a PR. If you then could have a look will be great
Cheers

**Comment by AntoniMarcinek** [comment]
Sure, I will have a look. Thank you!

**Comment by lmoneta** [comment]
@AntoniMarcinek  I have made a PR implementing the functionality you requested. 
Only the support for `_chg_truncated`, but it is not clear to me exactly what is it and what is your use case for this 
Cheers

**Comment by AntoniMarcinek** [comment]
@lmoneta I reviewed the PR, it looks great modulo some issues I mentioned in comments.

One thing which is not important to me, but does come to my mind is that dPDF and CDF seem to be settable only in 1D case. I think the multivariate methods of Unuran do accept gradients (dPDF?). So maybe you can consider adding this as well, but this is not my use case.

I will write about `_chg_truncated` later.

**Comment by AntoniMarcinek** [comment]
The `_chg_truncated` functions, e.g. `unur_hinv_chg_truncated` and `unur_tdr_chg_truncated`, change the range of sampled random variables without expensive reinitialization of the generator. So first one initializes the generator with a pdf with a domain (xmin, xmax) and later changes the range in which numbers are actually sampled from (xmin, xmax) to (xmin1, xmax1) which is a sub-range of (xmin, xmax). For methods which do not support this functionality the only option is to change the domain and reinitialize the generator.

My use case is that I have a pdf for which I need to change the sampling range for every sample, because it depends on kinematic limits for the given event, although the pdf does not change. Obviously reinitializing the generator would be very costly for the performance.

**Comment by lmoneta** [comment]
@AntoniMarcinek :  Thanks for the explanations of the _chg_truncated functions.
I will see if I can use them for some specific methods. I need to investigate what will be the best way of doing it, since these functions do not exist at a general level, but only at the specific method level.
