### ISSUE TITLE
xrdcp CLI tools should be installed or disabled

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7441]
Even though it's build and can be found in the build directory, it's not installed anymore. xrdcp is the default way to download files through the CLI, so I'd vote for having it back as part of the ROOT installation.

**Comment by stwunsch** [comment]
Update: We've found out that we actually never installed it but you got it via the source (via `thisroot.sh`) from the build directory. The focus now shifted toward whether we should disable building them at all to encourage everyone installing the xrootd CLI tools via the official sources.

**Comment by vepadulano** [comment]
My personal view: if one builds ROOT with `builtin_xrootd=ON` it means that they can't / don't want to install xrootd on their own, that also goes for xrootd binaries like `xrootd`,`xrdcp`. Thus, I would keep xrootd binaries in the ROOT build and install directories both. Following this reasoning, any other `builtin` option should install any binaries produced during the build process of the builtin package.

I think this from my limited experience with xrootd. I might be wrong, especially in extending the reasoning to other packages that I'm not expert of.

**Comment by stwunsch** [comment]
Same for LZMA and probably others, see https://github.com/root-project/root/pull/7542 for the PR to remove the executables for LZMA.

**Comment by eguiraud** [comment]
From the dedicated team meeting discussion, the decision was: "we will not install - and ideally not even build - binary artifacts of our builtins"

**Comment by vepadulano** [comment]
Closing this already solved issue :+1:

**Comment by eguiraud** [comment]
Looks like somehow at some point the behavior switched to not copy `xrdcp` & friends into the ROOT build's `bin` directory. They are still being built though, and they can be used from `<builddir>/builtins/xrootd/XROOTD-prefix/bin/xrdcp`

**Comment by vepadulano** [comment]
Since https://github.com/root-project/root/pull/7335 , xrootd is treated as other builtins in ROOT. That means it gets its own directory in the build process under `<builddir>/builtins/xrootd`. Before this change, the install directory for xrootd corresponded to the ROOT build directory, hence why the xrootd command line executables like `xrdcp` were installed in `<builddir>/bin`. Now all the build process of xrootd is properly confined in its builtin directory, so that in practice this issue is solved.
