### ISSUE TITLE
Problem initialising C++ class members from PyROOT through object properties

### ISSUE THREAD

**Issue by jblomer** [root-project/root#7501]
- [X] Checked for duplicates

### Describe the bug

C++ class members can be initialized in PyROOT through a constructor but it seems not working through object properties.  See details and reproducer in [the forum](https://root-forum.cern.ch/t/problem-initialising-c-class-members-from-pyroot/43970).

### Expected behavior

It should be possible to initialize class members through object properties.

### To Reproduce

See [forum post]([the forum](https://root-forum.cern.ch/t/problem-initialising-c-class-members-from-pyroot/43970).

**Comment by vepadulano** [comment]
cppyy-only reproducer

```python
#!/usr/bin/python

import numpy as np
import cppyy

cppyy.cppdef("""
#ifndef _test_class_h
#define  _test_class_h

#include <iostream>

class test_class
{
public:

    int track_length=0;
    float *v1 = nullptr; //[track_length]
    float *v2 = nullptr; //[track_length]


    test_class()
    {	
        std::cout << "default constr" << std::endl;
    };


    test_class(float *x, float *y, int tl)
    {
        v1 = x;
        v2 = y;
        track_length = tl;
    };

    void Set(float *x, float *y, int tl)
    {
        v1 = x;
        v2 = y;
        track_length = tl;
    };

};

#endif
""")

# Working
b = cppyy.gbl.test_class(np.array([24, 26], dtype=np.float32), np.array(
    [324, 25], dtype=np.float32), 2)
print(b.v1[0], b.v2[0])


# Working
b = cppyy.gbl.test_class()
b.Set(np.array([24, 26], dtype=np.float32),
      np.array([324, 25], dtype=np.float32), 2)
print(b.v1[0], b.v2[0])

# Not working - length 2
b = cppyy.gbl.test_class()
b.v1 = np.array([24, 25], dtype=np.float32)
b.v2 = np.array([324, 35], dtype=np.float32)
b.track_length = 2
b.v7 = np.array([2340, 235], dtype=np.float32)
print(b.v1[0], b.v1[1])
print(b.v2[0], b.v2[1])
print(b.v7)


# Not working - length 4
b = cppyy.gbl.test_class()
b.v1 = np.array([24, 25, 1, 3], dtype=np.float32)
b.v2 = np.array([324, 35, 7, 5], dtype=np.float32)
b.track_length = 4
b.v7 = np.array([2340, 235], dtype=np.float32)
print(b.v1[0], b.v1[1], b.v1[2], b.v1[3])
print(b.v2[0], b.v2[1], b.v2[2], b.v2[3])
print(b.v7)
```

Note the addition of a second "not working" snippet. With the original reproducer, printing all values of `v1` and `v2` arrays shows that they actually are the same as `v7`, whereas if the length of the first two arrays is longer than the length of the third, `v1` and `v2` are equal to each other and `v7` stays the same 
```
24.0 324.0
default constr
24.0 324.0
default constr
2340.0 235.0
2340.0 235.0
[2340.  235.]
default constr
324.0 35.0 7.0 5.0
324.0 35.0 7.0 5.0
[2340.  235.]
```

**Comment by wlav** [comment]
It's not a cppyy problem (and that is separate from the fact that this works fine as-is in cppyy master). You're storing pointers to temporaries. What is claimed to be "working" above are just cases where the deleted memory has not been overwritten with new data yet, because the arrays have the same lifetime (single statement). In the setting of properties case, the memory, if arrays are the same size, from one statement is re-used on the next statement. If you store the directly constructed `test_class` in a differently named variable and check it at the end of the script, there's a good chance that the values will be wrong at that point. I.e., for your fork, none of the above work.

The more common case is actually assigning `str` to `const char*`.
