### ISSUE TITLE
[RF] Silent but problematic backward incompatibility in RooConstVar (6.23+ --> earlier?)

### ISSUE THREAD

**Issue by will-cern** [root-project/root#7646]
I think there's a potentially nasty backward incompatibility issue arising from this commit: https://github.com/root-project/root/commit/90ba866a65bd44e74a995aa330e0a950114443d6#diff-896028fd27621f8bfe9d0774c5529e27df523e5bd7fcfe2ac54f6fd1ced316f9

Details of how the problem appeared to me are below, but I will say that the problem went away when I compiled 6.22 branch with the `_value` data member removed (since it masks the RooAbsReal one). I am guessing here that a RooConstVar version 2 written to disk isn't properly loaded as a RooConstVar version 1. But what is odd is that under some circumstances it seems that the const var value is correctly loaded -- it seems connected to if the arg is "dirty" or not. Sorry for being a bit vague, I dont fully understand why it is sometimes a problem and sometimes not but the problem goes away when the above commit is effectively ported back into 6.22

The issue first appeared for me when I opened a workspace (I wanted to attach to this issue but it wont let me attach a root file) created in 6.23.01 in 6.22.00 ... the only warning I get is: 

```
Warning in <TStreamerInfo::BuildOld>: Cannot convert RooRealVarSharedProperties::_altBinning from type: unordered_map<string,RooAbsBinning*> to type: RooLinkedList, skip element
```

But when I tried to evaluate the pdf in the workspace like this:

```
   RooWorkspace* w = f1.Get<RooWorkspace>("Test");
    auto func = w->pdf("SR_model");
    auto obs = w->var("obs_x_SR");
   func->getVal(*obs);
```

I got this:

```
 message      : p.d.f normalization integral is zero or negative: 0
 server values: !funcList=(L_x_bkg_SR_overallSyst_x_StatUncert = 47.1,L_x_sig_SR_overallSyst_x_StatUncert = 3.82), !coefList=(binWidth_obs_x_SR_0 = 5.5,binWidth_obs_x_SR_1 = 5.5)
```

**Comment by guitargeek** [comment]
Hi @will-cern, I realized now that this issue is still open. I think we have already discussed this at one of our meetings: RooFit doesn't aim for forward compatibility, so it is expected that you can't open a workspace with a newer ROOT version in an older one. If it works, then consider it just as luck :)

This is only supported for very commonly used classes like ROOT histograms.

I'll close this issue for now, feel free to open new ones for forward compatibility problems! That's what we want to ensure: old workspaces should be possible to read with any newer ROOT version.
