### ISSUE TITLE
hesse fails after calling getVal on nll

### ISSUE THREAD

**Issue by cburgard** [root-project/root#7659]
[workspace.root.zip](https://github.com/root-project/root/files/6196054/workspace.root.zip)

### Describe the bug

RooMinimizer::hesse() fails to find the correct hesse matrix if getVal has been used on the nll after minimize()

### Expected behavior

The hesse matrix should be independent of the number of calls to getVal()

### To Reproduce

Run this script on the attached workspace.

```
void test(){
  using namespace RooFit;
  
  TFile* infile = TFile::Open("workspace.root","READ");
  
  RooWorkspace * ws = (RooWorkspace*)(infile->Get("Test"));

  RooAbsData* data = ws->data("asimovData");
  RooAbsPdf* pdf = ws->pdf("simPdf");

  RooAbsReal* nll = pdf->createNLL(*data,NumCPU(1,3),Constrain(ws->argSet("norm_bkg,gamma_stat_CR_bin_0,gamma_stat_SR_bin_0,gamma_stat_SR_bin_1,gamma_stat_SR_bin_2,gamma_stat_SR_bin_3,gamma_stat_SR_bin_4,gamma_stat_SR_bin_5,gamma_stat_SR_bin_6,gamma_stat_SR_bin_7,gamma_stat_SR_bin_8,gamma_stat_SR_bin_9,gamma_stat_SR_bin_10,norm_bkg,gamma_stat_CR_bin_0,gamma_stat_SR_bin_0,gamma_stat_SR_bin_1,gamma_stat_SR_bin_2,gamma_stat_SR_bin_3,gamma_stat_SR_bin_4,gamma_stat_SR_bin_5,gamma_stat_SR_bin_6,gamma_stat_SR_bin_7,gamma_stat_SR_bin_8,gamma_stat_SR_bin_9,gamma_stat_SR_bin_10")),GlobalObservables(ws->argSet("nominalLumi,nom_gamma_stat_CR_bin_0,nom_gamma_stat_SR_bin_0,nom_gamma_stat_SR_bin_1,nom_gamma_stat_SR_bin_2,nom_gamma_stat_SR_bin_3,nom_gamma_stat_SR_bin_4,nom_gamma_stat_SR_bin_5,nom_gamma_stat_SR_bin_6,nom_gamma_stat_SR_bin_7,nom_gamma_stat_SR_bin_8,nom_gamma_stat_SR_bin_9,nom_gamma_stat_SR_bin_10,nominalLumi,nom_gamma_stat_CR_bin_0,nom_gamma_stat_SR_bin_0,nom_gamma_stat_SR_bin_1,nom_gamma_stat_SR_bin_2,nom_gamma_stat_SR_bin_3,nom_gamma_stat_SR_bin_4,nom_gamma_stat_SR_bin_5,nom_gamma_stat_SR_bin_6,nom_gamma_stat_SR_bin_7,nom_gamma_stat_SR_bin_8,nom_gamma_stat_SR_bin_9,nom_gamma_stat_SR_bin_10")));


  std::cout << "starting point : " << nll->getVal() << std::endl;
  RooArgSet params(*nll->getParameters((RooArgSet*)0));
  params.Print("v");
  
  gErrorIgnoreLevel = 0;
  ROOT::Minuit2::MnPrint::ClearFilter();
  ROOT::Math::MinimizerOptions::SetDefaultPrintLevel(2);
  
  RooMinimizer mini(*nll);
  mini.setMaxFunctionCalls(10000);
  mini.setMaxIterations(175000);
  mini.setPrintLevel(2);
  mini.optimizeConst(1);
  mini.setMinimizerType("Minuit2");
  mini.setEvalErrorWall(1);
  mini.setOffsetting(1);
  mini.setPrintEvalErrors(5);
  mini.setVerbose(0);
  mini.setProfile(1);
  mini.setStrategy(2);
  mini.setEps(0.001);
  
  std::cout << "starting minimization" << std::endl;
  
  mini.minimize("Minuit2","Migrad");

  // the call to nll->getVal() here seems to break it
  std::cout << "nll val at minimum is " << nll->getVal() << std::endl;
  
  mini.hesse();
}
```

**Comment by lmoneta** [comment]
The problem is not the step sizes. It is in the nll computed value. The minimizer computes the minimum nll to be  52.58, while `nll->getVal() returns `1163.66`. When calling `minmizer.hesse()` afterwards the nll value computed by the minimizer is also 1163 not consiustent with the minimum value and causing then a wrong Hesse computation. 
It is maybe some caching in the nll that behaves differently after calling `nll.getVal()`. I will investigate this

**Comment by cburgard** [comment]
I have seen before that the nll value is reported differently.
I think this is related to the LH offsetting.

**Comment by lmoneta** [comment]
Yes, offseting is the cause. I will try to fix it

**Comment by lmoneta** [comment]
The problem is more profound. It is in the handling of the offset, dirty flags and simultaneous fit. 
For a simultaneous fit the NLL is made of several components and the offset is computed and stored in the NLL components and not in the top level  NLL object. 
Now when you call again `nll->getVal()`  on the same data point, the calculation is not performed and RooFit returns the cached value, as it is done for every function in RooFit. The cached value is the one without the offset. 
Now when calling Hesse, the offset is enabled, but the central point of f(x) used for the derivative computation does not contain the offset. This explains the huge gradient obtained, because f(x+eps) has offset subtracted , while f(x) has not the offset. 
Adding this two lines before calling `hesse()`, fixes the problem: 
```
 auto mu = (RooRealVar*)params.find("mu");
  mu->setValueDirty();
```

A possible fix is being sure that the nll is in a dirty state when we start minimize() or hesse()
