### ISSUE TITLE
[PyROOT] Segfault calling TPython

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7678]
Following reproducer triggers a segfault in PyROOT:

```python
import cppyy
cppyy.gbl.TPython.Eval("1+1")
```

Because `TPython` is not part of cppyy, this is a ROOT issue. Also see comments in #7502.

**Comment by stwunsch** [comment]
See @wlav comment here: https://github.com/root-project/root/pull/7502#issuecomment-806218376

**Comment by etejedor** [comment]
This behaviour is understood (discussed already with @stwunsch). In a multi-python ROOT build, `TPython` is only compiled for the highest Python (i.e. Python3) and therefore it can only be used from that Python. The situation reported here only happens when using `TPython` from Python2 in a multi-python ROOT build, since `TPython` will trigger the loading of `libcppyy3_X` and `libcppyy_backend3_X`, thus causing the redefinition of symbols.
