### ISSUE TITLE
[VecOps] Introduce uppercase versions of mathematical functions such as abs, sqrt, sin, ...

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7697]
In the wake of our RDF focus group, we decided that we'd like to introduce also the uppercase versions of the mathematical functions in `ROOT::VecOps` to prevent confusion. Users are confused because the functions don't look like ROOT functions (lowercase) and because `std::abs` breaks but a plain `abs` works (because of the namespace deduction due to the function argument).

**Comment by jolly-chen** [comment]
I have created a PR that addresses this request. However, after some more consideration, I have two concerns:
- With this change, we would have both the PascalCase naming and the lowercase naming, which could lead to more confusion rather than clarification. Also, what about other RVec methods such as `size` and `at`? These are still lowercase only.
- While PascalCase aligns with the naming conventions of ROOT, it seems like lowercase naming was an intentional choice for RVec to make RVec a drop-in replacement for std::vector (see https://github.com/root-project/root/blob/b8e267afe416700024c63667f06b0408c6704bac/math/vecops/inc/ROOT/RVec.hxx#L1350). So should we stick to lowercase instead?

**Comment by vepadulano** [comment]
This issue was brought up for discussion within the team. As things currently stand, the benefits of introducing the uppercase version of these function in the `VecOps` namespace is not clear. The decision is to close this issue for now, if more users will identify this as a blocker for their use cases then we can reassess the decision. Thanks a lot @jolly-chen for taking the time to address this!
