### ISSUE TITLE
[Doc] Tutorial not correctly shown

### ISSUE THREAD

**Issue by stwunsch** [root-project/root#7802]
See the distrdf tutorial here:
https://root.cern/doc/master/distrdf001__spark__connection_8py.html

The code of the Python tutorial is not shown like normally, e.g. https://root.cern/doc/master/df107__SingleTopAnalysis_8py.html.

**Comment by couet** [comment]
I see the problem when I build the doc locally on my machine. But the macro does not work for me:
```
% python /Users/couet/git/couet-root/tutorials/dataframe/distrdf001_spark_connection.py
Traceback (most recent call last):
  File "/Users/couet/git/couet-root/tutorials/dataframe/distrdf001_spark_connection.py", line 19, in <module>
    import pyspark
ImportError: No module named pyspark

```

**Comment by vepadulano** [comment]
Hi Olivier,
thanks for taking a look at this! Indeed this tutorial depends on pyspark, which is one of our optional runtime dependencies since 6.24,  as also described in [requirements.txt](https://github.com/root-project/root/blob/master/requirements.txt). I can run the tutorial on my machine and it also works on our CI nodes where I installed `pyspark`, so I think it's probably some issue with `\macro_code` and similar magic we use for the tutorials, I'm not very familiar with those

**Comment by stwunsch** [comment]
You can also just comment out all relevant code and dump some random stuff there. I would guess it's the used markup around that code, it's likely that this will give you already a reproducer.

**Comment by couet** [comment]
\macro_code just display the code but  \macro_image runs the macro to generate the image. See the description here: https://root.cern/for_developers/doxygen/#tutorials-documentation .So \macro_image is failing because of the missing pyspark. If you remove \macro_image (if you do not need the image) then the tutorial web page is properly generated.

**Comment by couet** [comment]
I let you decide what to do.

**Comment by stwunsch** [comment]
@couet Could you install pyspark on the docs machine?

**Comment by couet** [comment]
@stwunsch : The machine running the installation of the reference guide is root-ubuntu-2004-2. I logged on this machine and simply tried (stupidly) to type "pyspark". I know nothing about this tool but surprisingly I got an answer saying it seems wrongly installed there ... Dod you have an idea about that ? what should be done ? A  Python expert might know better.

```
sftnight@root-ubuntu-2004-2:~$ pyspark
Could not find valid SPARK_HOME while searching ['/home', '/usr/local/bin']

Did you install PySpark via a package manager such as pip or Conda? If so,
PySpark was not found in your Python environment. It is possible your
Python environment does not properly bind with your package manager.

Please check your default 'python' and if you set PYSPARK_PYTHON and/or
PYSPARK_DRIVER_PYTHON environment variables, and see if you can import
PySpark, for example, 'python -c 'import pyspark'.

If you cannot import, you can install by using the Python executable directly,
for example, 'python -m pip install pyspark [--user]'. Otherwise, you can also
explicitly set the Python executable, that has PySpark installed, to
PYSPARK_PYTHON or PYSPARK_DRIVER_PYTHON environment variables, for example,
'PYSPARK_PYTHON=python3 pyspark'.

/usr/local/bin/pyspark: line 24: /bin/load-spark-env.sh: No such file or directory
/usr/local/bin/pyspark: line 68: /bin/spark-submit: No such file or directory
sftnight@root-ubuntu-2004-2:~$ 

```

**Comment by stwunsch** [comment]
Indeed, it's already there for python3! ->

```
$ python3
Python 3.8.5 (default, Jan 27 2021, 15:41:15)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyspark
```

Which python version is the docs build using?

**Comment by stwunsch** [comment]
I've now also installed pyspark for python2. Can you confirm that this fixes the issue?

**Comment by stwunsch** [comment]
Fixed!
