### ISSUE TITLE
Changes in Clang do not rebuild Clad

### ISSUE THREAD

**Issue by hahnjo** [root-project/root#7977]
### Describe the bug
As seen in #7488, changing headers / data structures in Clang doesn't rebuild Clad and causes very weird test failures.

### Expected behavior
The build system should detect the changes and rebuild Clad as well as `libCling.so` as needed.

### To Reproduce
Apply / Revert #7488 to see a crash or just touch Clang header files and observe that Clad isn't rebuilt.

**Comment by hahnjo** [comment]
Not sure who to assign, feel free to change...

**Comment by vgvassilev** [comment]
I am not sure how we can fix this issue. The cmake `ExternalProject_Add` is meant to operate on projects which are not changed in tree. There seems to be an option: BUILD_ALWAYS <bool> which says " Enabling this option forces the build step to always be run. This can be the easiest way to robustly ensure that the external project's own build dependencies are evaluated rather than relying on the default success timestamp-based method. This option is not normally needed unless developers are expected to modify something the external project's build depends on in a way that is not detectable via the step target dependencies (e.g. SOURCE_DIR is used without a download method and developers might modify the sources in SOURCE_DIR)."

That would fix this problem but introduce another one -- clad would be rebuilt every time one types `make`. ROOT has good amount of uses of `ExternalProject_Add` and that kind of issue is not only specific to clad. 

I think we have several options: a) close the bug and ignore that type of errors (which can waste dev debug time); b) add BUILD_ALWAYS and waste a lot of user/dev time; c) check if it is feasible to somehow track changes in the source code within the regular cmake (which probably has proven hard and people added the BUILD_ALWAYS option).

**Comment by hahnjo** [comment]
I'm ok to close this; it will probably pop up again in the future, but I agree that rebuilding Clad every time is a higher time sink for the team than one developer having to investigate weird failures. And by now, we hopefully have a sufficient understanding that it will take less time in the future because we know how to "fix" it.

**Comment by dpiparo** [comment]
Since @hahnjo is OK to close it, we close it. Please do not hesitate to re-open in case more information becomes available that suggests to revisit this decision.

**Comment by vgvassilev** [comment]
Let's close it. It is annoying but the `ExternalProject_Add` is supposed to bring in projects as they are and it does not expect to have development or any major changes in there.

**Comment by hahnjo** [comment]
Ok, but it's not fixed in 6.30.06! I've adjusted the projects accordingly.
