### ISSUE TITLE
[cling] backport patch from llvm 13~dev to fix problem with -fgpu-rdc

### ISSUE THREAD

**Issue by SimeonEhrig** [root-project/root#8112]
### Describe the bug

To support CUDA `__constant__` memory and `__device__` points [CUDA separate compiling](https://developer.nvidia.com/blog/separate-compilation-linking-cuda-device-code/) is necessary, which will be enabled by the flag `-fgpu-rdc`.

Related issues:
* https://github.com/root-project/cling/issues/396
* https://github.com/root-project/cling/issues/395

Unfortunately, there is a bug in Clang 9, which disturbs the function. A bug fix is implemented in the current Clang 13-dev branch: https://github.com/llvm/llvm-project/commit/b008ea304d438f0aa818918caceb3bd864412304#diff-4d89d3c6d6aa954d6d77426520d881efefc4eb631dbe25730c4599c0b5150ec6 and https://github.com/llvm/llvm-project/commit/0b2af1a2889423bb797856841ac81cf10d01c696 

Thanks to @hahnjo for finding it.

@hahnjo, @vgvassilev and I have already discussed in the issue https://github.com/root-project/cling/issues/396 that a backport could cause a lot of work because of AMD's HIP development. On the other hand, it will take some time before Cling is upgraded to LLVM 13. Therefore, backporting this fix would be very useful so that I can continue my work.

**Comment by hahnjo** [comment]
Hi @SimeonEhrig, I'm not sure backporting the fix is a) feasible and b) sufficient. As already mentioned in the other issue, that part of Clang has seen massive changes due to AMD upstreaming their HIP programming model (and fixing quite a number of CUDA issues along the way). The fix for `extern __constant__` is really only https://github.com/llvm/llvm-project/commit/b008ea304d438f0aa818918caceb3bd864412304 (but there are many other fixes for problems that you might or might not encounter later on); the reason I mentioned https://github.com/llvm/llvm-project/commit/0b2af1a2889423bb797856841ac81cf10d01c696 is that it refactored that part of the code and introduced the functions that are modified for the fix. I tried applying both of them (in chronological order, obviously) and it doesn't work cleanly. I had a quick look at `git log` for only `clang/lib/CodeGen/CGCUDANV.cpp` and found the massive https://github.com/llvm/llvm-project/commit/5be9b8cbe2b2253f78a09a863bef18e574737465 that overhauled the registration logic to add support for surfaces and textures. It only appeared in LLVM 11, so we'd either have to backport that as well or re-implement the fix(es) in terms of what is currently there.

Moreover, I'm not sure if Clang already knows how to register relocatable `__device__` functions and `extern __constant__` variables or that it needs to invoke `nvlink` to produce an uploadable GPU binary. I didn't implement support for that back then, and I couldn't find in the history that somebody reverse engineered the magic since then. I'm not very familiar with Cling's support for CUDA compilation, but I'd assume that proper support in Clang itself would be a requirement to make it work.

Sorry if my current take on the matter sounds a bit disappointing. I'd be happy to have a chat about possible ways around the issues, but I probably can't put much of my time on CUDA support in Cling...

**Comment by SimeonEhrig** [comment]
Hi @hahnjo, thanks for the clarification. Now I understand what you mean.

> Sorry if my current take on the matter sounds a bit disappointing. I'd be happy to have a chat about possible ways around the issues, but I probably can't put much of my time on CUDA support in Cling...

This is not disappointing. It just means that I need another strategy ;-) It's good to know that it's probably not efficient to backport the code, so I can save time. Besides, the need for the feature has also decreased a bit since we found a workaround for [clad](https://github.com/vgvassilev/clad). This was the main reason why I wanted to implement this feature.

Therefore I think will start with reengineering of `nvlink`. It is also needed, I can implement it with with Clang and later integrate it in Cling when it is updated to LLVM 12/13.

**Comment by hahnjo** [comment]
I'm closing this for now, see https://github.com/root-project/root/issues/8112#issuecomment-839789038
