### ISSUE TITLE
Python iteration over a TTreeReader is broken

### ISSUE THREAD

**Issue by eguiraud** [root-project/root#8183]
### Describe the bug

Here's a self-contained reproducer:

```python
import ROOT

ROOT.RDataFrame(10).Define("x", "int(rdfentry_)").Snapshot("t", "f.root")

f = ROOT.TFile("f.root")
t = f.Get("t")
reader = ROOT.TTreeReader(t)
age = ROOT.TTreeReaderValue['int'](reader, "x")
staff_list = []
for entry in reader:
    print(age.Get()[0])
```

This prints

```
1
2
3
4
5
6
7
8
9
9
```

instead of 

```
0
1
2
3
4
5
6
7
8
9
```

### Expected behavior

Either Python iteration should be disabled (in favor of `while reader.Next()`, which works as expected) or it should produce the same results as the `while reader.Next()` loop.

### Additional context

First reported at https://root-forum.cern.ch/t/ttreereader-vs-rdataframe-vs-branches-to-read-ttree/44785

**Comment by etejedor** [comment]
It seems that the iterator is working properly, but not its interplay with `TTreeReaderValue`, which is somehow decoupled.

Continuing with the example above:

```python
>>> it = iter(reader)
>>> reader.GetCurrentEntry()
-1
>>> next(it)
0
>>> reader.GetCurrentEntry()
1
>>> age.Get()[0]
1
```

The iterator, when invoking `next(it)`, returns the correct entry number (0). But once that's done, the current entry has already moved to 1, which is why `age.Get()[0]` returns 1 too. This does not happen with `TTreeReader::Next()` because after the first call to `Next()`, we are in entry 0:

```python
>>> reader.GetCurrentEntry()
-1
>>> reader.Next()
True
>>> reader.GetCurrentEntry()
0
```

Therefore a new iterator that relied on `Next()` could work.

**Comment by eguiraud** [comment]
Uhm but why does the first `next(it)` call increment the entry number twice?

**Comment by etejedor** [comment]
> Uhm but why does the first next(it) call increment the entry number twice?

Actually it does not increment it twice, because the iterator is created with entry number 0:

https://github.com/root-project/root/blob/master/tree/treeplayer/inc/TTreeReader.h#L240

So the entry number in the iterator goes from 0 to 1 after the first `next(it)` (the old one is returned), but in the reader it goes from -1 to 1 here:

https://github.com/root-project/root/blob/master/tree/treeplayer/inc/TTreeReader.h#L110

**Comment by etejedor** [comment]
> So e.g. in C++ the increment happens at the end of the first iteration and in Python it happens at the beginning?

Yes, when you are inside the loop body in the first iteration in Python, a call to `next(iter)` has already been made. See e.g. if we run this in Python, the reader entry is always one step ahead:

```python
>>> for entry_num in reader: print(entry_num, reader.GetCurrentEntry())
... 
0 1
1 2
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10
```

whereas in C++ what I observe is:
```c++
root [1] for (auto entry_num: reader) { cout << entry_num << " " << reader.GetCurrentEntry() << endl; }
0 0
1 1
2 2
3 3
4 4
5 5
6 6
7 7
8 8
9 9
```

**Comment by eguiraud** [comment]
How does this difference not break _every_ usage of C++ iterators from Python? this seems to be a generic incompatibility -- C++ iterators are meant to be instantiated -> dereferenced -> incremented, while from Python they end up being instantiated -> incremented -> dereferenced.

**Comment by etejedor** [comment]
> How does this difference not break every usage of C++ iterators from Python? this seems to be a generic incompatibility -- C++ iterators are meant to be instantiated -> dereferenced -> incremented, while from Python they end up being instantiated -> incremented -> dereferenced.

I think it's because here there is some decoupling iterator - reader. What the iterator actually returns works well (the entry number), it's the link with the entry of the reader that fails.

For example, `RooArgSet` works out of the box, and the iterator returns a `RooRealVar` which is what we want in the end:
```python
>>> import ROOT
>>> 
>>> x = ROOT.RooRealVar("x", "x", -10, 10) 

RooFit v3.60 -- Developed by Wouter Verkerke and David Kirkby 
                Copyright (C) 2000-2013 NIKHEF, University of California & Stanford University
                All rights reserved, please read http://roofit.sourceforge.net/license.txt

>>> y = ROOT.RooRealVar("y", "y", -10, 10) 
>>> 
>>> args = ROOT.RooArgSet(x, y)
>>> 
>>> for elm in args:
...     print(elm.GetName(), type(elm))
... 
x <class cppyy.gbl.RooRealVar at 0x5b9ad00>
y <class cppyy.gbl.RooRealVar at 0x5b9ad00>
```
