### ISSUE TITLE
Cannot compile root to produce static libraries

### ISSUE THREAD

**Issue by maxnoe** [root-project/root#8448]
- [X] Checked for duplicates

### Describe the bug

I am compiling root including the `-DBUILD_SHARED_LIBS=OFF` option that according to https://root.cern/install/build_from_source/#relevant-cmake-variables should result in static libraries to be compiled.

However, when running this, I still get shared libraries in the install location:

### Expected behavior

Getting static libs in the install direction:

```
❯ ls static-root/lib/*.so | wc -l
105
❯ ls static-root/lib/*.a | wc -l
zsh: no matches found: static-root/lib/*.a
0
```

### To Reproduce

```
$ curl -L https://root.cern/download/root_v6.24.00.source.tar.gz | tar xz    
$ mkdir root-build
$ cmake  -S ./root-6.24.00/ -B root-build \
	-DCMAKE_INSTALL_PREFIX=$HOME/.local/static-root \
	-DBUILD_SHARED_LIBS=off \
	-Dxrootd=off -Dmysql=off -Dpgsql=off -Dpyroot=off \
	-Droofit=off -Ddataframe=off -Dspectrum=off -Dtmva=off \
	-Dfitsio=off -Dfftw3=off
$ cmake --build root-build -- -j 8
$ cmake --install root-build
```

### Setup
Manjaro using gcc 11.1, root version 6.24.0

**Comment by Axel-Naumann** [comment]
I think we should just remove the option `-DBUILD_SHARED_LIBS` rather than fixing it - we are requiring shared library magic e.g. for hiding our own llvm+clang.

@maxnoe what's the motivation for a static build?

**Comment by maxnoe** [comment]
We wanted to produce a relocatable executable statically linking root.

**Comment by Axel-Naumann** [comment]
Thanks. Is the goal is to make the installation trivial, or what's the motivation?

**Comment by maxnoe** [comment]
Yes, ease of deployment.

**Comment by Axel-Naumann** [comment]
OK. We `dlopen` `libCling` into the process, some other files (`.pcm`, headers, plugin files) must be available as well. Because of this we never invested energy in static builds: you won't get a "one file packaged ROOT" anyway.

I'd like to understand your use case a bit - what is it that you are trying to solve? How is the deployment of a regular ROOT build inappropriate / not easy enough?

**Comment by maxnoe** [comment]
@VukanJ can comment on this, he brought it up in hour group

**Comment by VukanJ** [comment]
The idea was to have an executable that is linked statically against ROOT and other dependencies so that it can be used as the legacy version of a certain software package which is being retired in favour of new  software. For example in order to run it using a gitlab runner for various cross-checks without the need to install root from source (multiple times even, for every testing stage) or ship it together with huge CentOS images. For the gitlab this just seems to be almost unfeasible, even with existing root docker containers from the docker hub. I understand that if ROOT was never meant to be used in this way, there just won't be resources to dedicate to this. So I will probably have to find a way to access such an exectuable from somewhere else while running those tests or run them offline. Nevertheless, having the `BUILD_SHARED_LIBS` flag available now, can be misleading, that point stands on its own of course

**Comment by maxnoe** [comment]
@VukanJ that flag is a CMake builtin, but it should probably be removed from the building documentation, since it does not really apply to ROOT then as advertised

**Comment by Axel-Naumann** [comment]
Thanks, we'll update the build docs. Note that CentOS brings ROOT in through EPEL - not sure whether that's sufficient for your case.

Sad to hear that you're leaving ROOT!

**Comment by Axel-Naumann** [comment]
Please let me know if you want this issue here to be reopened, because https://github.com/root-project/root/issues/8532 doesn't capture what needs to be done!
