### ISSUE TITLE
RLogger warnings

### ISSUE THREAD

**Issue by ferdymercury** [root-project/root#8458]
- [x] Checked for duplicates

### Describe the bug
When using ROOT::RFile in my projects, I get some compiler warnings:

```
In file included from /opt/root_bld/include/ROOT/RDirectory.hxx:20,
                 from /opt/root_bld/include/ROOT/RFile.hxx:19,
                 from zdt-daq/gui/MainWindow.cpp:49:
/opt/root_bld/include/ROOT/RLogger.hxx: In member function ‘void ROOT::Experimental::RLogDiagCount::Increment(ROOT::Experimental::ELogLevel)’:
/opt/root_bld/include/ROOT/RLogger.hxx:72:14: warning: enumeration value ‘kUnset’ not handled in switch [-Wswitch-enum]
       switch (severity) {
              ^
/opt/root_bld/include/ROOT/RLogger.hxx:72:14: warning: enumeration value ‘kInfo’ not handled in switch [-Wswitch-enum]
/opt/root_bld/include/ROOT/RLogger.hxx:72:14: warning: enumeration value ‘kDebug’ not handled in switch [-Wswitch-enum]
/opt/root_bld/include/ROOT/RLogger.hxx: At global scope:
/opt/root_bld/include/ROOT/RLogger.hxx:136:7: warning: base class ‘class ROOT::Experimental::RLogChannel’ has accessible non-virtual destructor [-Wnon-virtual-dtor]
 class RLogManager : public RLogChannel, public RLogHandler {
       ^~~~~~~~~~~
```

### Expected behavior
No warnings are found

### Setup
1. ROOT master
2. Ubuntu 19
3. Self-built

**Comment by Axel-Naumann** [comment]
I don't understand the first warning - my line `RLogger.hxx:76` is
```cpp
      default:;
```
which should have silenced this warning? What are the warning flags you use? Is this Ubuntu 19.10 or 19.04 (both are end of life, btw.) with GCC 8.3? I cannot reproduce this warning in a [stand-alone example](https://www.godbolt.org/z/Kv7TqY61h), so I must be missing something.

The second "issue" actually tells me that you are using `-Weffc++` which we don't support in ROOT since many many years now: it did not serve us well, causing many bogus changes just to make `-Weffc++` happy. Here, too, the warning is just not relevant: yes, we know that we cannot delete an object of type `RLogManager` through a pointer to `RLogChannel`, but we are not going to do that. OTOH we cannot make the dtor of `RLogChannel` protected because we actually have objects of that type.

So please don't build your ROOT headers with `-Weffc++`, an consider replacing `-Weffc++` with some more helpful static analysis.

I will leave this open until we understand the first issue better.

**Comment by ferdymercury** [comment]
I disabled Weffc++ now, and indeed that warning disappears.

I was using gcc 8.4.0

I think the first warning comes because I was using `-Wswitch-enum` which warns even with a default, so I guess I will remove this flag too. Thanks!

**Comment by Axel-Naumann** [comment]
Thanks for your reply, all makes sense now!
