### ISSUE TITLE
FYI - standalone C implementation of ranluxpp 

### ISSUE THREAD

**Issue by jirka-h** [root-project/root#8504]
FYI - I have created a standalone implementation of ranluxpp written in C based on your code. You can check it here:

https://github.com/jirka-h/ranluxpp-portable

**Comment by hahnjo** [comment]
Thanks for letting us know, but I'm not sure if we want to link another implementation from ROOT's documentation - @lmoneta?

A few comments on the repository:
 * There doesn't seem to be a function to extract numbers from the state. `ranluxpp-test.c` suggests to use 64 bit numbers, which is neither the 52 bits in Sibidanov's implementation nor the 48 bits that ROOT returns since the latest update to retain the connection to the theoretical properties.
 * AFAICT the generator is based on the older version that didn't convert the LCG state back to RANLUX numbers. Please see Section 2.3 of our paper for possible issues regarding a bias in the bits from the LCG state.

**Comment by jirka-h** [comment]
Hallo Jonas,

thanks a lot for the feedback! My initial interest was to measure the speed of the new implementation. 

I have now checked Section 2.3 of [your paper](https://arxiv.org/pdf/2106.02504.pdf) and I have missed this important point! I will add this to my code. 

Thanks for the review.
Jirka

**Comment by jirka-h** [comment]
I have opened a new issue to track the progress:

https://github.com/jirka-h/ranluxpp-portable/issues/1

**Comment by hahnjo** [comment]
@jirka-h FYI, I uploaded a C++ standalone version into https://github.com/hahnjo/ranluxpp

**Comment by jirka-h** [comment]
This is great:-) 

Thank you, Jonas! 

Please see my comments here:
https://github.com/hahnjo/ranluxpp/issues/1
