### ISSUE TITLE
[DF] Add support for 'missing' columns

### ISSUE THREAD

**Issue by pcanal** [root-project/root#8704]
`TTree::Draw` supports a special function `Alt$` which allows to specify a value to be used if a column (or element of a collection) in missing.  RDataFrame could use a similar feature (for example `DefineAlternative(column_name, alternative_value)`.  [As a side note, `TTreeReaderValue` currently seem to complain if the underlying column is missing).

**Comment by eguiraud** [comment]
To clarify, the plan is to have something like a `DefineDefault("x", ...)` to provide default values for a branch when it's not present in the dataset.

**Comment by vepadulano** [comment]
Bump https://root-forum.cern.ch/t/only-perform-define-on-events-where-branch-exists/57943/2

**Comment by eguiraud** [comment]
My bad for not managing to get to this in time. I think most of the logic would go in `GetColumnReader`, in `ColumnReaderUtils`: it would have to create a `TreeColumnReader` if the column is present in the tree and pick the reader for the default value instead.

The main complication is dealing with chains in which _some_ trees contain the column and some do not.
The most direct way to do it is leveraging TChain's callback mechanism to switch column readers as needed, but a) TChain's callback mechanism is a mess and b) even if unused TTreeReaderValues for missing branches might emit warnings (unless they are completely destroyed maybe?).
An more roundabout way to do the same would be to change single-thread RDataFrame so that it runs a separate event loop for each sub-tree and never uses a TChain --> you automatically get a call to `GetColumnReader` that can re-evaluate whether the branch or the default value should be used at the start of every new event loop.

Finally, you can implement the default as a `Define` that always returns the same number (and in first approximation that's probably the easiest). A slightly nicer underlying implementation would involve a `ConstReader` that explicitly stores a constant value and always returns that same value, but the advantage is unclear -- a good optimizing compiler would elide the call to the lambda that always returns the same number anyways.

**Comment by vepadulano** [comment]
This PR, among other things, also introduces the requested `DefaultFor` feature https://github.com/root-project/root/pull/15641
