### ISSUE TITLE
Minuit2: FCNGradientBase::CheckGradient() is ignored

### ISSUE THREAD

**Issue by HDembinski** [root-project/root#8716]
This patch
https://github.com/root-project/root/commit/ae9f8ae62553f9150fdee1f8739be6996d539694
had an unintended side-effect. The code to check the external gradient against the numerical gradient when `CheckGradient()` returns `true` is now never executed.

Whether the user provides an analytical gradient or not, only this implementation is called
https://github.com/root-project/root/blob/master/math/minuit2/src/MnSeedGenerator.cxx#L42
while the other implementation is now never executed
https://github.com/root-project/root/blob/master/math/minuit2/src/MnSeedGenerator.cxx#L103

I suggest to revert https://github.com/root-project/root/commit/ae9f8ae62553f9150fdee1f8739be6996d539694, because it also confused iminuit users, see https://github.com/scikit-hep/iminuit/issues/644. People usually use the analytical gradient only when the calculation of the likelihood is extremely expensive, and then it is undesired that some gradients are still computed numerically.

**Comment by guitargeek** [comment]
The `CheckGradient()` interface was removed, since it had no effect as you said:
https://github.com/root-project/root/commit/94549da66304cd9a94a256620abb09e5fbd1079d

It's also on our radar that numeric gradients are still used for things like the seeding step. We're working towards making Minuit 2 "numeric gradient free" as well. If you think this should be tracked separately, feel free to re-open a new issue about this specific subject! Thanks for your input.
