### ISSUE TITLE
Avoid needing to type `ROOT.ROOT` twice in PyROOT

### ISSUE THREAD

**Issue by vepadulano** [root-project/root#8745]
### Describe the bug

In PyROOT it has been possible to avoid the double `ROOT.ROOT` for some classes/functions for a while
```py
import ROOT
df = ROOT.RDataFrame
```
But that doesn't happen for every new class/function defined in C++ . This is a simple reproducer: create some entities in a namespace:
```py
import ROOT

ROOT.gInterpreter.Declare(
"""
namespace ROOT{
namespace Detail{
struct MyStruct{};
void dostuff(){}
int myint;
}}
"""
)
```
Then try to access them in a Python session
```py
$ python -i namespace_function.py
>>> ROOT.Detail.MyStruct
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: <namespace cppyy.gbl.Detail at 0x55e51fdc7f50> has no attribute 'MyStruct'. Full details:
  type object 'Detail' has no attribute 'MyStruct'
  'Detail::MyStruct' is not a known C++ class
  'MyStruct' is not a known C++ template
  'MyStruct' is not a known C++ enum
>>> ROOT.ROOT.Detail.MyStruct
<class cppyy.gbl.ROOT.Detail.MyStruct at 0x55e51fe1dd60>
>>> ROOT.Detail.dostuff
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: <namespace cppyy.gbl.Detail at 0x55e51fdc7f50> has no attribute 'dostuff'. Full details:
  type object 'Detail' has no attribute 'dostuff'
  'Detail::dostuff' is not a known C++ class
  'dostuff' is not a known C++ template
  'dostuff' is not a known C++ enum
>>> ROOT.ROOT.Detail.dostuff
<cppyy.CPPOverload object at 0x7f522b684eb0>
>>> ROOT.Detail.myint
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: <namespace cppyy.gbl.Detail at 0x55e51fdc7f50> has no attribute 'myint'. Full details:
  type object 'Detail' has no attribute 'myint'
  'Detail::myint' is not a known C++ class
  'myint' is not a known C++ template
  'myint' is not a known C++ enum
>>> ROOT.ROOT.Detail.myint
0
```

It's unclear how to avoid the double `ROOT.ROOT` in general.

### Expected behavior

Be able to avoid typing the name twice, at least for classes/functions defined in ROOT source code.

### Setup

ROOT master on Fedora32

**Comment by etejedor** [comment]
To add some more information after some investigation with @vepadulano: when doing `ROOT.Detail.MyStruct`, the `Detail` namespace that PyROOT returns is the one in the global namespace, i.e. `Detail`, not `ROOT::Detail`. This happens because, when doing a lookup from Python in the `ROOT` module, the global namespace is inspected first, and only if that lookup fails the `ROOT` namespace is tried. But since `Detail` already exists in the global namespace, `ROOT::Detail` is never returned - and `Detail` does not contain any `MyStruct`. Bottom line: the PyROOT lookup works as expected.

That being said, we found a weird behavior with the `Detail` namespace, which can be reproduced from Python and also from C++ in the ROOT prompt:

```
root [0] auto c = TClass::GetClass("Detail")
(TClass *) @0x7fffd0908fc0
root [1] namespace Detail { int i; }
root.exe: /home/etejedor/root/fork/root/interpreter/llvm/src/include/llvm/Support/Casting.h:105: static bool llvm::isa_impl_cl<To, const From*>::doit(const From*) [with To = clang::TagType; From = clang::Type]: Assertion `Val && "isa<> used on a null pointer"' failed.
```

If we look up the `Detail` namespace first and then define something else in it, there is a crash. I will open another ticket to follow this up.
