### ISSUE TITLE
RNTuple: Can not create a Field for a user class with anonymous enum 

### ISSUE THREAD

**Issue by Nowakus** [root-project/root#8901]
RFieldBase::Create("fieldname", "classame") in ROOT 6.24.0 returns an error when the class contains an anonymous enum. 
To reproduce execute a ROOT macro EmumTest.C containing:
```
class ContainsEnum { public:  enum { EnumField1, EnumField2 }; };   
void EnumTest() {   
  try {  auto field = ROOT::Experimental::Detail::RFieldBase::Create("HasEnum", "ContainsEnum").Unwrap();   
  } catch(const std::exception& exc) {   
      std::cout << "ERROR: " << exc.what() << std::endl;   
  }   
}
``` 
```root [0] 
Processing EnumTest.C...
ERROR: Field EnumField1 has unknown type ContainsEnum::(anonymous) (unchecked RResult access!)
At:
  static ROOT::Experimental::RResult<std::unique_ptr<ROOT::Experimental::Detail::RFieldBase> > ROOT::Experimental::Detail::RFieldBase::Create(const string&, const string&) [/build/jenkins/workspace/lcg_release_pipeline/build/projects/ROOT-v6.24.00/src/ROOT/v6.24.00/tree/ntuple/v7/src/RField.cxx:225]
```
Marcin

**Comment by jblomer** [comment]
It turns out that `TClass::GetListOfDataMembers()` returns an item for the constants in old, unscoped enums (anonymous or not) that are defined in the class. For instance, in the example above, `GetListOfDataMembers()` returns an item for `EnumField1` and `EnumField2`. This is not the case for an `enum class`.

I'm wondering if this is the expected bahavior?  If it is, I consider the following approach to distinguish an enum declaration from an actual data member:
  1. Build a set of pointers from `GetListOfRealData()` ... `GetDataMember()`.
  2. Filter out from `GetListOfDataMembers()` those that are not in the set of 1.

NB: This approach does not work with `GetListOfRealData()` ... `GetName()` because the list of real data also has the members from base classes and the following example:
```
struct A : {
  int E;
};
struct B : A {
  enum { E };
};
```

@pcanal Does that make sense?

**Comment by jblomer** [comment]
@pcanal One more question: if I use `GetListOfRealData` on a class hierarchy where I only have a dictionary for the derived class but not for the base class, I get a segmentation fault. Is it expected?

**Comment by pcanal** [comment]
> if I use GetListOfRealData on a class hierarchy where I only have a dictionary for the derived class but not for the base class, I get a segmentation fault. Is it expected?

No it is not.
