### ISSUE TITLE
Implement an RDataFrame::Merge(RDataFrame &df) function.

### ISSUE THREAD

**Issue by acampove** [root-project/root#9030]
### Is your feature request related to a problem? Please describe.
Instances of `RDataFrame` objects are meant to be treated like trees. Therefore there should be a function that allows us to merge them. Without this, we would do things like:

```python
#-----------------------------------------
def get_tree(filepath, index):
    df= ROOT.RDataFrame('tree', filepath)
    df= df.Define('identity', index)
    df.Snapshot('tree', '/tmp/{}.root'.format(index))

    ifile = ROOT.TFile('/tmp/{}.root'.format(suf))
    itree = ifile.tree

    return (ifile, itree)
#-----------------------------------------
def merge(filepath_1, filepath_2):
        if_1, itree_1 = get_tree(file_path_1, '1')
        if_2, itree_2 = get_tree(file_path_2, '2')

        ofile = ROOT.TFile('file.root', 'recreate')
        l_tree = ROOT.TList()
        l_tree.Add(itree_1)
        l_tree.Add(itree_2)

        otree = ROOT.TTree.MergeTrees(l_tree)
        otree.Write()
        ofile.Close()
```

which requires opening each file and saving them. Then loading them again and merging, then saving again, this is all wasteful and time consuming.

### Describe the solution you'd like

```python
df_1=ROOT.RDataFrame('tree', file_path_1)
df_2=ROOT.RDataFrame('tree', file_path_2)

df_1=df_1.Define('identity', '+1')
df_2=df_2.Define('identity', '+2')

df_3 = df_1.Merge(df_2)
df_3.Snapshot('tree', 'file.root')
```

### Describe alternatives you've considered

I am currently using the `get_trees` and `merge` functions I wrote, but it's far from ideal, it takes ages to finish.

**Comment by vepadulano** [comment]
We should probably wait for @eguiraud for a final answer, but I'd like to give my two cents about this.

> Instances of RDataFrame objects are meant to be treated like trees.

I am curious about this first sentence. I have never got this impression, neither reading docs / toying with tutorials or doing more complex analyses with RDF. the first line of the [RDF docs](https://root.cern/doc/master/classROOT_1_1RDataFrame.html) says `ROOT's RDataFrame offers a high level interface for analyses of data stored in TTree, CSV's and other data formats. `.  Just by the fact that I can read and process other formats than TTree I would say that in general RDF is not meant to be treated like a TTree. Otherwise I would also have to say that RDF is meant to be treated like a CSV file or something similar.

> there should be a function that allows us to merge them

If I have to think about this function you propose, I don't see it going much further than the example you already have above. Since RDataFrame **is not** the dataset itself, but just an interface to it, it still needs to open the file where the dataset is contained and read data from it. Thus, merging two RDF objects would still involve ` opening each file and saving them. Then loading them again and merging, then saving again` as you say above. Or at least the loading, merging and saving again part, if we consider that the part of your example where you create two files from scratch and save data into them with RDF could also just have been opening already existing files written by some other application before the merging. In fact the solution you provide follows exactly these steps:
 ```python
# Opening files and loading pre-existing datasets
 df_1=ROOT.RDataFrame('tree', file_path_1)
df_2=ROOT.RDataFrame('tree', file_path_2)

# creating new columns in the datasets
df_1=df_1.Define('identity', '+1')
df_2=df_2.Define('identity', '+2')

# Merging the datasets in memory
df_3 = df_1.Merge(df_2)
# Opening a new file and save the merged dataset into the new file
df_3.Snapshot('tree', 'file.root')
```

I admit that I might not be able to see some internal optimizations that RDF might do while merging, but the logical steps seem to be equivalent to me. Or I also might be misinterpreting your proposal.

## Current possible approaches

If you need to process a dataset with RDF and need to concatenate parts of it, the current best approach is to use the `RDataFrame(TTree &tree)` constructor after having created the correct tree with all the information you need. If for example you need to concatenate vertically 2 or more TTrees (i.e. if all have the same schema with column `a` and you want to append values of the same column into a single entity), than you can create a TChain and add all the trees to it. If you need horizontal concatenation (i.e. the trees have different schema but same number of entries) you can use friends pattern (e.g. `tree.AddFriend`). This has the big advantage that you don't need to merge any of the files/trees together and thus you also don't need to save them again before creating the RDF object. At the same time, once you do create the RDF object with this concatenated dataset, you will still be able to call `Snapshot` and get practically a "merged" dataset in your output file

**Comment by acampove** [comment]
Dear @vepadulano 

Thanks for your reply.

> Dear @acampove,
> Thanks contacting us. We should probably wait for @eguiraud for a final answer, but I'd like to give my two cents about this.
> 
> > Instances of RDataFrame objects are meant to be treated like trees.
> 
> I am curious about this first sentence. I have never got this impression, neither reading docs / toying with tutorials or doing more complex analyses with RDF. the first line of the [RDF docs](https://root.cern/doc/master/classROOT_1_1RDataFrame.html) says `ROOT's RDataFrame offers a high level interface for analyses of data stored in TTree, CSV's and other data formats. `. Just by the fact that I can read and process other formats than TTree I would say that in general RDF is not meant to be treated like a TTree. Otherwise I would also have to say that RDF is meant to be treated like a CSV file or something similar.

I did not refer to the documentation but to how people would actually use this class. 99% of people do not read CSV files with ROOT and `RDataFrame` will be mostly used to interact in a simple and quick way with trees.

> 
> > there should be a function that allows us to merge them
> 
> If I have to think about this function you propose, I don't see it going much further than the example you already have above. Since RDataFrame **is not** the dataset itself, but just an interface to it, it still needs to open the file where the dataset is contained and read data from it. Thus, merging two RDF objects would still involve ` opening each file and saving them. Then loading them again and merging, then saving again` as you say above. Or at least the loading, merging and saving again part, if we consider that the part of your example where you create two files from scratch and save data into them with RDF could also just have been opening already existing files written by some other application before the merging. In fact the solution you provide follows exactly these steps:
> 
> ```python
> # Opening files and loading pre-existing datasets
> df_1=ROOT.RDataFrame('tree', file_path_1)
> df_2=ROOT.RDataFrame('tree', file_path_2)
> 
> # creating new columns in the datasets
> df_1=df_1.Define('identity', '+1')
> df_2=df_2.Define('identity', '+2')
> 
> # Merging the datasets in memory
> df_3 = df_1.Merge(df_2)
> # Opening a new file and save the merged dataset into the new file
> df_3.Snapshot('tree', 'file.root')
> ```
> 
> I admit that I might not be able to see some internal optimizations that RDF might do while merging, but the logical steps seem to be equivalent to me. Or I also might be misinterpreting your proposal.

No, the approaches are different. In the approach without `RDataFrame::Merge` I save twice the modified trees with the new column added, so the whole thing is slower than the second approach where the looping and saving can be done only once. 

> 
> ## Current possible approaches
> If you need to process a dataset with RDF and need to concatenate parts of it, the current best approach is to use the `RDataFrame(TTree &tree)` constructor after having created the correct tree with all the information you need. If for example you need to concatenate vertically 2 or more TTrees (i.e. if all have the same schema with column `a` and you want to append values of the same column into a single entity), than you can create a TChain and add all the trees to it. If you need horizontal concatenation (i.e. the trees have different schema but same number of entries) you can use friends pattern (e.g. `tree.AddFriend`). This has the big advantage that you don't need to merge any of the files/trees together and thus you also don't need to save them again before creating the RDF object. At the same time, once you do create the RDF object with this
concatenated dataset, you will still be able to call `Snapshot` and get practically a "merged" dataset in your output file

OK, I agree with this and this is a third approach what you propose. The trees can be added as a chain to the `RDataFrame`, the chain can get branches added with `Define` and then `Snapshot` would make a merged version. This would probably mean looping and saving only once and it is efficient. However what if we have 3 trees in the brach and we need a branch `index` whose value is `1` for the first tree `2` for the second and `3` for the third. How would we do that with `Define`? Stuff like:

```python
df = df.Define('index', 'GetTreeNumber() + 1')
```

would not work, right?

Cheers.

> 
> Cheers,
> Vincenzo

**Comment by eguiraud** [comment]
Hi,
assuming that simply producing a single tree to begin with is impossible, I would also recommend to go with a TChain for post-processing.

> what if we have 3 trees in the brach and we need a branch index whose value is 1 for the first tree 2 for the second and 3 for the third. How would we do that with Define?

Is it not possible to store these indexes in the trees when they are produced? If not, currently you have three possible solutions that I can think of:

- calculate the index from the value of `rdfentry_`, knowing how many entries are in each tree and their ordering inside the TChain
- store some unique identifier in each tree when it's produced (even a timestamp works, and although it's not elegant you don't have to worry about having that same value stored in each event because it will compress almost perfectly, occupying very little extra space on disk). With that unique identifier per tree you can build another tree that serves as a lookup table between id and index. It will have two branches, `id` and `index`, with the first taking the values of the ids of each tree and the second being an index from 0 to nTrees-1. Then you can use `TTree::BuildIndex` and `TChain::AddFriend` to add that lookup table tree as a friend of the original chain and thanks to `BuildIndex` the correct value of `index` will be returned for each event depending on the value of `id` in the original chain. More info at https://root.cern/manual/trees/#indexing-trees
- do a pass on each input tree to calculate whatever other quantities you need to calculate (let's call these trees `aux1`, `aux2` etc.), then make a TChain out of the original trees, another TChain out of the `aux` trees, and then add the second chain as a friend of the first (effectively creating a single large "virtual" TTree with everything in it)

The simplest solution: with the upcoming `DefinePerSample` method you can solve this more easily, but the feature will only be merged in ROOT master in a few days ([PR here](https://github.com/root-project/root/pull/8841)). With `DefinePerSample` you could write something like this:

```cpp
df.DefinePerSample("index", "GetIndex(rdfsampleinfo_.AsString())")
```

where `rdfsampleinfo_.AsString()` will be of the form `<filename>/<treename>`. I expect to merge this feature in master today or tomorrow.

**Comment by acampove** [comment]
Hi,

> Hi, assuming that simply producing a single tree to begin with is impossible, I would also recommend to go with a TChain for post-processing.

These trees are produced from jobs in the grid, it is not possible to produce a single file.
> 
> > what if we have 3 trees in the brach and we need a branch index whose value is 1 for the first tree 2 for the second and 3 for the third. How would we do that with Define?
> 
> Is it not possible to store these indexes in the trees when they are produced? If not, currently you have three possible solutions that I can think of:

It is possible to do that. However those trees do not have those indexes and in order to add them we would need to rerun hundreds of jobs in the grid. We do need to postprocess these ntuples anyway, so the idea is to slip in a small function to add this index. 
> 
> * calculate the index from the value of `rdfentry_`, knowing how many entries are in each tree and their ordering inside the TChain

It is dangerous and requires adding too many lines of code.

> * store some unique identifier in each tree when it's produced (even a timestamp works, and although it's not elegant you don't have to worry about having that same value stored in each event because it will compress almost perfectly, occupying very little extra space on disk). With that unique identifier per tree you can build another tree that serves as a lookup table between id and index. It will have two branches, `id` and `index`, with the first taking the values of the ids of each tree and the second being an index from 0 to nTrees-1. Then you can use `TTree::BuildIndex` and `TChain::AddFriend` to add that lookup table tree as a friend of the original chain and thanks to `BuildIndex` the correct value of `index` will be returned for each event depending on the value of `id` in the original chain. More info at https://root.cern/manual/trees/#indexing-trees

We would have to run again all the jobs in the grid to store a unique ID. However the name of the file identifies it, so we deduce the index with the filename. The rest of the solution is close to what I did below.
 
> * do a pass on each input tree to calculate whatever other quantities you need to calculate (let's call these trees `aux1`, `aux2` etc.), then make a TChain out of the original trees, another TChain out of the `aux` trees, and then add the second chain as a friend of the first (effectively creating a single large "virtual" TTree with everything in it)

OK, that is closer to what we need, I managed to get the code below to add these indexes in a slightly different way from what you said (or maybe the same if I misunderstood you), i.e. using chains and friend trees:

```python
import ROOT

import numpy
#------------------------------------------
def make_data(val):
    val = str(val)
    filepath = '/tmp/file_{}.root'.format(val)

    df=ROOT.RDataFrame(2)
    df=df.Define('a', val)
    df.Snapshot('tree', filepath)

    return filepath
#------------------------------------------
def get_df(l_tp_file, treename, id_column='index'):
    l_index = []
    for index, filepath in l_tp_file:
        df=ROOT.RDataFrame(treename, filepath)
        nentries = df.Count().GetValue()
        l_index += nentries * [index]

    arr_id = numpy.array(l_index)

    idfilepath = '/tmp/file_id.root'
    df_id = ROOT.RDF.MakeNumpyDataFrame({id_column: arr_id})
    df_id.Snapshot(treename, idfilepath)

    ch_data = ROOT.TChain(treename, '') 
    for _, filepath in l_tp_file:
        ch_data.Add(filepath)

    size_ch = ch_data.GetEntries()
    size_id = arr_id.size

    if size_ch != size_id:
        print('Different id and chain sizes: {}/{}'.format(size_id, size_ch))
        raise

    ch_data.AddFriend(treename, idfilepath)

    df = ROOT.RDataFrame(ch_data)

    return (df, ch_data)
#------------------------------------------
def test():
    #----------------------
    #Make input
    #----------------------
    index = 0 
    l_tp_file = []  
    for val in range(0, 100, 10):
        filepath = make_data(val)
        l_tp_file.append((index, filepath))
        index+=1
    #----------------------
    #Merge
    #----------------------
    df, _ = get_df(l_tp_file, 'tree', id_column='id')
    df.Display(['a', 'id'], -1).Print()
    #df.Snapshot('tree', 'file.root')
#------------------------------------------
test()
```

I will add `get_df` to my personal library. The approach seems safe and clean enough, however the return value needs to include the chain (i.e. _) because otherwise I get a crash. Which seems to indicate that the chain's reference is not kept inside the dataframe. So once the function returns, the chain is removed by the garbage collector and the dataframe does not have anything to save (the script above is self contained and you can try it yourself). That should not be right, if I tell the dataframe to use the chain, the chain should be kept alive by the dataframe.

> 
> The simplest solution: with the upcoming `DefinePerSample` method you can solve this more easily, but the feature will only be merged in ROOT master in a few days ([PR here](https://github.com/root-project/root/pull/8841)). With `DefinePerSample` you could write something like this:
> 
> ```c++
> df.DefinePerSample("index", "GetIndex(rdfsampleinfo_.AsString())")
> ```
> 
> where `rdfsampleinfo_.AsString()` will be of the form `<filename>/<treename>`. I expect to merge this feature in master today or tomorrow.

So we would have to create a `GetIndex` function to extract from the "filename/treename" the index? Yes, that would make my code far simpler. However it might take months until that is available through CVMFS. In any case, the simpler our code gets, the better, fewer places for bugs to hide.

Cheers and thanks.

**Comment by acampove** [comment]
Hi @eguiraud ,

OK, thanks for your help, that function does give us more flexibility. I closed the issue already.

Cheers.
