### ISSUE TITLE
[cling] `error: function definition is not allowed here` when trying to overload `operator<=`

### ISSUE THREAD

**Issue by sbmorphe** [root-project/root#9449]
When trying to define an operator in the cling cli repl, the "function definition is not allowed here" error is generated. "cling -version" reports "0.8". Here's a copy/paste of a session to demonstrate the issue:

<pre>
****************** CLING ******************
* Type C++ code and press enter to run it *
*             Type .q to exit             *
*******************************************
[cling]$ #include &lt;iostream>
[cling]$ using namespace std;
[cling]$ struct A {
[cling]$ ?   A(int val1, int val2) : pod1(val1), pod2(val2) {}
[cling]$ ?   int pod1, pod2;
[cling]$ ?   };
[cling]$ bool operator<=(const A &lhs, const A &rhs) {
[cling]$ ?   return ((lhs.pod1 <= rhs.pod1) && (lhs.pod2 <= rhs.pod2));
[cling]$ ?   }
input_line_6:2:46: error: function definition is not allowed here
 bool operator<=(const A &lhs, const A &rhs) {
                                             ^
</pre>

**Comment by jalopezg-r00t** [comment]
@sbmorphe, thanks for reporting!  This is a good catch!

In this case, cling is trying to wrap the input as it thinks `bool operator<=(...)` is not a valid function declarator -presumably due to the `<=`.  This seems to be another limitation of the current strategy to generate wrapper functions.

See also the related issue #9171.  @vgvassilev and I recently talked about this, which has to be addressed also for clang-repl.

As a workaround, you can either temporarily turn on raw input, or define the function in an anonymous namespace, i.e.
```c++
[cling]$ .rawInput 1
[cling]$ bool operator<=(const A &lhs, const A &rhs) { return ((lhs.pod1 <= rhs.pod1) && (lhs.pod2 <= rhs.pod2)); }
[cling]$ .rawInput 0
```
or
```c++
[cling]$ namespace { bool operator<=(const A &lhs, const A &rhs) { return ((lhs.pod1 <= rhs.pod1) && (lhs.pod2 <= rhs.pod2)); } }
```
