### ISSUE TITLE
lambda expressions in TF1 - pyroot

### ISSUE THREAD

**Issue by danielbattistini** [root-project/root#9465]
Hi,
I'm trying to use lambda expressions to define TF1 objects.
Inside python I run the following code:
`from ROOT import TF1`
`f = TF1('f', lambda x: x[0], 0, 1)`
`f.Draw()`

but I get a blank canvas and this error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/alice/sw/ubuntu2004_x86-64/ROOT/v6-24-06-13/lib/ROOT/_application.py", line 68, in displayhook
    gInterpreter.EndOfLineAction()
TypeError: void TInterpreter::EndOfLineAction() =>
    TypeError: callable was deleted
```

I'm using pyroot inside the AliPhysics environment. I tested these lines on 4 different machines that use different versions of python: 3.6, 3.7, 3.8 and 3.9. Only with the two older versions it runs as expected. For python 3.8 and 3.9 the error message is the same.

Do you know what might be the cause of this behavior with newer versions of python?

**Comment by etejedor** [comment]
The problem here is that the lambda you are passing to the constructor of `TF1` is a temporary that is (can be) garbage collected right after the constructor call of `TF1` returns. That's what the `callable was deleted` error is saying.

If you define the lambda beforehand and bind it to a variable so that it's still alive when you draw, you can solve that problem:
```python
from ROOT import TF1
l = lambda x: x[0]
f = TF1('f', l, 0, 1)
f.Draw()
```

The fact that it was working with other versions of Python was by pure chance (the object was still not deleted).

**Comment by etejedor** [comment]
Closing this issue, please let me know if you have any other problem.
