### ISSUE TITLE
[RF] Cannot turn off useless messages with RooMCStudy unbinned fits + Progress bar would be better.

### ISSUE THREAD

**Issue by acampove** [root-project/root#9489]
### Explain what you would like to see improved
When running:
```c++
#include "RooRealVar.h"
#include "RooGaussian.h"
#include "RooAddPdf.h"
#include "RooMCStudy.h"

using namespace RooFit;

void rf801_mcstudy()
{
   RooRealVar x("x", "x", 0, 10);
   x.setBins(40);

   RooRealVar mean("mean", "", 5, 0, 10);
   RooRealVar sigma("sg", "", 0.5);
   RooGaussian pdf("pdf", "", x, mean, sigma);

   RooMCStudy *mcstudy = new RooMCStudy(pdf, x, Binned(kTRUE), Silence(true), Extended(true), FitOptions(Save(kTRUE), PrintEvalErrors(0)));
   //RooMCStudy *mcstudy = new RooMCStudy(pdf, x, Binned(kFALSE), Silence(true), Extended(true), FitOptions(Save(kTRUE), PrintEvalErrors(0))
   mcstudy->generateAndFit(1000, 1000);
}
```
![image](https://user-images.githubusercontent.com/14037062/147851308-1eb033f3-94ea-4e53-a88b-f7e017a278aa.png)

which is not ideal, here a progress bar would be better, it would prevent the screen from been filled. However, having a 10 fits step seems reasonable. 

On the other hand, when running the fit with unbinned data (uncomment the line in the code above), I see:

![image](https://user-images.githubusercontent.com/14037062/147851372-3197ea2f-d44c-4cd7-ae03-e92389ddb6a3.png)

which is a terrible design. It completely fills the monitor with 1000 lines of useless information. The only way that I found to silence this is doing something like:

```python
msg  = ROOT.RooMsgService.instance()
str_z=msg.getStream(0)
str_z.minLevel = ROOT.RooFit.WARNING
```
which also turns off the `PROGRESS` message telling me how many toys have been run. So either I make it hide everything or I get 1000 messages.

### Optional: share how it could be improved
If I would have time I would:

1. Make the `now generating` message a `DEBUG` one.
2. Use a progress bar for the `run` message.

### To Reproduce
You can just run the code I put above.

### Setup
1. ROOT version: 6.24/06
2. Operating system: Linux manjaro 5.15.7-1-MANJARO
3. How you obtained ROOT, such as `dnf install` / binary download / you built it yourself: Manjaro package manager, probably related to pacman.

**Comment by guitargeek** [comment]
Hi @acampove, thanks for reporting this issue!

I have opened a to avoid the overly-verbose printout in the unbinned case:
https://github.com/root-project/root/pull/14309

However, I would refrain from implementing a progress bar, because this makes the output more difficult to digest when reading log files from e.g. grid jobs. So while I agree it would be nice for interactive use, it would do more harm that good in batch jobs. One could maybe hack something that detects the context in which RooFit is used, but these hacks are usually fragile and I would prefer not to do it.

I'll close this issue after merging the PR with the log in the unbinned case. If you *really* want this progress bar, feel free to open a new issue about this, but I'm afraid I can't justify giving that one a high priority.

Thanks for your understanding!
Jonas
